FROM node:22-alpine

WORKDIR /app/frontend

COPY frontend/package.json ./package.json

RUN npm config set registry https://registry.npmmirror.com && npm install --verbose

COPY frontend /app/frontend
COPY workflow_apps /app/workflow_apps

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
