// This file is auto-generated by @hey-api/openapi-ts

export const AdminUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        namespace_assignments: {
            items: {
                $ref: '#/components/schemas/UserNamespaceAssignment'
            },
            type: 'array',
            title: 'Namespace Assignments',
            default: []
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'AdminUserCreate'
} as const;

export const AdminUserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        namespace_assignments: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/UserNamespaceAssignment'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Namespace Assignments'
        }
    },
    type: 'object',
    title: 'AdminUserUpdate'
} as const;

export const AgentEventTypeSchema = {
    type: 'string',
    enum: [
        'user_message',
        'assistant_message',
        'tool_call',
        'tool_result',
        'status',
        'error',
        'result'
    ],
    title: 'AgentEventType'
} as const;

export const ArtifactKindSchema = {
    type: 'string',
    enum: [
        'agent',
        'skill',
        'mcp',
        'cli_config',
        'workspace_content'
    ],
    title: 'ArtifactKind'
} as const;

export const ArtifactPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        kind: {
            $ref: '#/components/schemas/ArtifactKind'
        },
        logical_target: {
            $ref: '#/components/schemas/LogicalTarget'
        },
        version: {
            type: 'string',
            title: 'Version'
        },
        content_sha256: {
            type: 'string',
            title: 'Content Sha256'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        manifest: {
            additionalProperties: true,
            type: 'object',
            title: 'Manifest'
        },
        signature: {
            type: 'string',
            title: 'Signature'
        },
        signing_public_key: {
            type: 'string',
            title: 'Signing Public Key'
        }
    },
    type: 'object',
    required: [
        'id',
        'kind',
        'logical_target',
        'version',
        'content_sha256',
        'size',
        'manifest',
        'signature',
        'signing_public_key'
    ],
    title: 'ArtifactPublic'
} as const;

export const ArtifactsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/ArtifactPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'ArtifactsPublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_login-login_access_token'
} as const;

export const Body_runtime_artifacts_upload_artifactSchema = {
    properties: {
        kind: {
            $ref: '#/components/schemas/ArtifactKind'
        },
        logical_target: {
            $ref: '#/components/schemas/LogicalTarget'
        },
        version: {
            type: 'string',
            maxLength: 128,
            minLength: 1,
            title: 'Version'
        },
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: [
        'kind',
        'logical_target',
        'version',
        'file'
    ],
    title: 'Body_runtime-artifacts-upload_artifact'
} as const;

export const ClaimInputSchema = {
    properties: {
        worker_id: {
            type: 'string',
            title: 'Worker Id'
        }
    },
    type: 'object',
    required: [
        'worker_id'
    ],
    title: 'ClaimInput'
} as const;

export const DeploymentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        node_id: {
            type: 'string',
            format: 'uuid',
            title: 'Node Id'
        },
        artifact_id: {
            type: 'string',
            format: 'uuid',
            title: 'Artifact Id'
        },
        previous_artifact_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Previous Artifact Id'
        },
        attempt: {
            type: 'integer',
            title: 'Attempt'
        },
        status: {
            $ref: '#/components/schemas/DeploymentStatus'
        },
        error: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: [
        'id',
        'node_id',
        'artifact_id',
        'previous_artifact_id',
        'attempt',
        'status',
        'error'
    ],
    title: 'DeploymentPublic'
} as const;

export const DeploymentStatusSchema = {
    type: 'string',
    enum: [
        'pending',
        'dispatched',
        'applied',
        'failed',
        'expired'
    ],
    title: 'DeploymentStatus'
} as const;

export const EnrollmentTokenCreatedSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        token: {
            type: 'string',
            title: 'Token'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        }
    },
    type: 'object',
    required: [
        'id',
        'token',
        'expires_at'
    ],
    title: 'EnrollmentTokenCreated'
} as const;

export const EnrollmentTokenPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        },
        consumed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Consumed At'
        },
        revoked_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Revoked At'
        }
    },
    type: 'object',
    required: [
        'id',
        'expires_at',
        'consumed_at',
        'revoked_at'
    ],
    title: 'EnrollmentTokenPublic'
} as const;

export const EnrollmentTokensPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/EnrollmentTokenPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'EnrollmentTokensPublic'
} as const;

export const EventBatchSchema = {
    properties: {
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        events: {
            items: {
                $ref: '#/components/schemas/EventInput'
            },
            type: 'array',
            title: 'Events'
        }
    },
    type: 'object',
    required: [
        'task_id',
        'events'
    ],
    title: 'EventBatch'
} as const;

export const EventInputSchema = {
    properties: {
        sequence: {
            type: 'integer',
            title: 'Sequence'
        },
        event_type: {
            $ref: '#/components/schemas/AgentEventType'
        },
        payload: {
            additionalProperties: true,
            type: 'object',
            title: 'Payload'
        }
    },
    type: 'object',
    required: [
        'sequence',
        'event_type',
        'payload'
    ],
    title: 'EventInput'
} as const;

export const EventPublicSchema = {
    properties: {
        sequence: {
            type: 'integer',
            title: 'Sequence'
        },
        event_type: {
            $ref: '#/components/schemas/AgentEventType'
        },
        payload: {
            additionalProperties: true,
            type: 'object',
            title: 'Payload'
        }
    },
    type: 'object',
    required: [
        'sequence',
        'event_type',
        'payload'
    ],
    title: 'EventPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: [
        'title'
    ],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'title',
        'id',
        'owner_id'
    ],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'ItemsPublic'
} as const;

export const LeaseInputSchema = {
    properties: {
        worker_id: {
            type: 'string',
            title: 'Worker Id'
        },
        revision: {
            type: 'integer',
            title: 'Revision'
        }
    },
    type: 'object',
    required: [
        'worker_id',
        'revision'
    ],
    title: 'LeaseInput'
} as const;

export const LlmProviderCatalogFieldSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        required: {
            type: 'boolean',
            title: 'Required',
            default: true
        },
        placeholder: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Placeholder'
        },
        help_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Help Text'
        }
    },
    type: 'object',
    required: [
        'name',
        'label'
    ],
    title: 'LlmProviderCatalogField'
} as const;

export const LlmProviderCatalogItemSchema = {
    properties: {
        provider_slug: {
            type: 'string',
            title: 'Provider Slug'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        auth_type: {
            $ref: '#/components/schemas/ProviderAuthType'
        },
        default_base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Base Url'
        },
        supports_health_check: {
            type: 'boolean',
            title: 'Supports Health Check'
        },
        supports_model_discovery: {
            type: 'boolean',
            title: 'Supports Model Discovery'
        },
        base_url_editable: {
            type: 'boolean',
            title: 'Base Url Editable'
        },
        secret_fields: {
            items: {
                $ref: '#/components/schemas/LlmProviderCatalogField'
            },
            type: 'array',
            title: 'Secret Fields',
            default: []
        },
        extra_fields: {
            items: {
                $ref: '#/components/schemas/LlmProviderCatalogField'
            },
            type: 'array',
            title: 'Extra Fields',
            default: []
        }
    },
    type: 'object',
    required: [
        'provider_slug',
        'display_name',
        'auth_type',
        'supports_health_check',
        'supports_model_discovery',
        'base_url_editable'
    ],
    title: 'LlmProviderCatalogItem'
} as const;

export const LlmProviderCatalogPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/LlmProviderCatalogItem'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'LlmProviderCatalogPublic'
} as const;

export const LlmProviderConfigCreateSchema = {
    properties: {
        config_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Config Name'
        },
        provider_slug: {
            type: 'string',
            maxLength: 128,
            minLength: 1,
            title: 'Provider Slug'
        },
        base_url: {
            type: 'string',
            maxLength: 1024,
            minLength: 1,
            title: 'Base Url'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: true
        },
        extra_config: {
            additionalProperties: true,
            type: 'object',
            title: 'Extra Config'
        },
        secret_inputs: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Secret Inputs'
        },
        manual_models: {
            items: {
                $ref: '#/components/schemas/LlmProviderModelInput'
            },
            type: 'array',
            title: 'Manual Models',
            default: []
        },
        enabled_model_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Enabled Model Ids',
            default: []
        }
    },
    type: 'object',
    required: [
        'config_name',
        'provider_slug',
        'base_url'
    ],
    title: 'LlmProviderConfigCreate'
} as const;

export const LlmProviderConfigPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        namespace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Namespace Id'
        },
        config_name: {
            type: 'string',
            title: 'Config Name'
        },
        provider_slug: {
            type: 'string',
            title: 'Provider Slug'
        },
        provider_display_name: {
            type: 'string',
            title: 'Provider Display Name'
        },
        auth_type: {
            $ref: '#/components/schemas/ProviderAuthType'
        },
        base_url: {
            type: 'string',
            title: 'Base Url'
        },
        secret_masked: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secret Masked'
        },
        extra_config: {
            additionalProperties: true,
            type: 'object',
            title: 'Extra Config',
            default: {}
        },
        supports_health_check: {
            type: 'boolean',
            title: 'Supports Health Check'
        },
        supports_model_discovery: {
            type: 'boolean',
            title: 'Supports Model Discovery'
        },
        validation_status: {
            $ref: '#/components/schemas/ProviderValidationStatus'
        },
        validation_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Validation Message'
        },
        last_validated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Validated At'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        models: {
            items: {
                $ref: '#/components/schemas/LlmProviderModelPublic'
            },
            type: 'array',
            title: 'Models',
            default: []
        }
    },
    type: 'object',
    required: [
        'id',
        'namespace_id',
        'config_name',
        'provider_slug',
        'provider_display_name',
        'auth_type',
        'base_url',
        'supports_health_check',
        'supports_model_discovery',
        'validation_status',
        'enabled'
    ],
    title: 'LlmProviderConfigPublic'
} as const;

export const LlmProviderConfigUpdateSchema = {
    properties: {
        config_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Config Name'
        },
        base_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Url'
        },
        enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled'
        },
        secret_inputs: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secret Inputs'
        },
        extra_config: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra Config'
        },
        manual_models: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/LlmProviderModelInput'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Manual Models'
        },
        enabled_model_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled Model Ids'
        }
    },
    type: 'object',
    title: 'LlmProviderConfigUpdate'
} as const;

export const LlmProviderConfigsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/LlmProviderConfigPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'LlmProviderConfigsPublic'
} as const;

export const LlmProviderModelInputSchema = {
    properties: {
        model_id: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Model Id'
        },
        display_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Name'
        }
    },
    type: 'object',
    required: [
        'model_id'
    ],
    title: 'LlmProviderModelInput'
} as const;

export const LlmProviderModelPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        model_id: {
            type: 'string',
            title: 'Model Id'
        },
        display_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Name'
        },
        source_type: {
            $ref: '#/components/schemas/ProviderModelSourceType'
        },
        is_enabled: {
            type: 'boolean',
            title: 'Is Enabled'
        },
        sync_status: {
            $ref: '#/components/schemas/ProviderModelSyncStatus'
        },
        raw_metadata: {
            additionalProperties: true,
            type: 'object',
            title: 'Raw Metadata',
            default: {}
        },
        last_synced_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Synced At'
        }
    },
    type: 'object',
    required: [
        'id',
        'model_id',
        'source_type',
        'is_enabled',
        'sync_status'
    ],
    title: 'LlmProviderModelPublic'
} as const;

export const LlmProviderSyncModelsRequestSchema = {
    properties: {
        manual_models: {
            items: {
                $ref: '#/components/schemas/LlmProviderModelInput'
            },
            type: 'array',
            title: 'Manual Models',
            default: []
        },
        enabled_model_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Enabled Model Ids',
            default: []
        }
    },
    type: 'object',
    title: 'LlmProviderSyncModelsRequest'
} as const;

export const LogicalTargetSchema = {
    type: 'string',
    enum: [
        'agents',
        'skills',
        'mcp',
        'cli',
        'workspace'
    ],
    title: 'LogicalTarget'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: [
        'message'
    ],
    title: 'Message'
} as const;

export const MessageInputSchema = {
    properties: {
        prompt: {
            type: 'string',
            minLength: 1,
            title: 'Prompt'
        }
    },
    type: 'object',
    required: [
        'prompt'
    ],
    title: 'MessageInput'
} as const;

export const NamespaceCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        code: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Code'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        admin_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Admin User Id'
        }
    },
    type: 'object',
    required: [
        'name',
        'code'
    ],
    title: 'NamespaceCreate'
} as const;

export const NamespacePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        code: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Code'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'name',
        'code',
        'id'
    ],
    title: 'NamespacePublic'
} as const;

export const NamespaceRoleSchema = {
    type: 'string',
    enum: [
        'admin',
        'developer',
        'user'
    ],
    title: 'NamespaceRole'
} as const;

export const NamespaceUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Code'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        admin_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Admin User Id'
        }
    },
    type: 'object',
    title: 'NamespaceUpdate'
} as const;

export const NamespaceUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        role: {
            $ref: '#/components/schemas/NamespaceRole',
            default: 'user'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'NamespaceUserCreate'
} as const;

export const NamespaceUserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        role: {
            anyOf: [
                {
                    $ref: '#/components/schemas/NamespaceRole'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'NamespaceUserUpdate'
} as const;

export const NamespacesPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/NamespacePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'NamespacesPublic'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'token',
        'new_password'
    ],
    title: 'NewPassword'
} as const;

export const NodeEnrollInputSchema = {
    properties: {
        token: {
            type: 'string',
            minLength: 16,
            title: 'Token'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        hostname: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Hostname'
        },
        os_name: {
            type: 'string',
            maxLength: 128,
            minLength: 1,
            title: 'Os Name'
        },
        architecture: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Architecture'
        },
        agent_version: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Agent Version'
        },
        sdk_version: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sdk Version'
        },
        public_key: {
            type: 'string',
            title: 'Public Key'
        }
    },
    type: 'object',
    required: [
        'token',
        'name',
        'hostname',
        'os_name',
        'architecture',
        'agent_version',
        'public_key'
    ],
    title: 'NodeEnrollInput'
} as const;

export const NodeEnrollResultSchema = {
    properties: {
        node_id: {
            type: 'string',
            format: 'uuid',
            title: 'Node Id'
        },
        namespace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Namespace Id'
        },
        credential: {
            type: 'string',
            title: 'Credential'
        },
        credential_expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Credential Expires At'
        }
    },
    type: 'object',
    required: [
        'node_id',
        'namespace_id',
        'credential',
        'credential_expires_at'
    ],
    title: 'NodeEnrollResult'
} as const;

export const NodePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        hostname: {
            type: 'string',
            title: 'Hostname'
        },
        os_name: {
            type: 'string',
            title: 'Os Name'
        },
        architecture: {
            type: 'string',
            title: 'Architecture'
        },
        agent_version: {
            type: 'string',
            title: 'Agent Version'
        },
        sdk_version: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sdk Version'
        },
        online: {
            type: 'boolean',
            title: 'Online'
        },
        last_seen_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Seen At'
        },
        revoked_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Revoked At'
        },
        runtime_profile_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Runtime Profile Id'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'hostname',
        'os_name',
        'architecture',
        'agent_version',
        'sdk_version',
        'online',
        'last_seen_at',
        'revoked_at',
        'runtime_profile_id'
    ],
    title: 'NodePublic'
} as const;

export const NodeRuntimePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        node_id: {
            type: 'string',
            format: 'uuid',
            title: 'Node Id'
        },
        route_mode: {
            $ref: '#/components/schemas/RuntimeRouteMode'
        },
        model_id: {
            type: 'string',
            title: 'Model Id'
        },
        provider_config_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider Config Id'
        },
        base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Url'
        },
        permission_mode: {
            type: 'string',
            title: 'Permission Mode'
        },
        secret_masked: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secret Masked'
        }
    },
    type: 'object',
    required: [
        'id',
        'node_id',
        'route_mode',
        'model_id',
        'provider_config_id',
        'base_url',
        'permission_mode',
        'secret_masked'
    ],
    title: 'NodeRuntimePublic'
} as const;

export const NodeRuntimeUpsertSchema = {
    properties: {
        route_mode: {
            $ref: '#/components/schemas/RuntimeRouteMode'
        },
        model_id: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Model Id'
        },
        provider_config_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider Config Id'
        },
        base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Url'
        },
        permission_mode: {
            type: 'string',
            title: 'Permission Mode',
            default: 'default'
        },
        secret_inputs: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secret Inputs'
        }
    },
    type: 'object',
    required: [
        'route_mode',
        'model_id'
    ],
    title: 'NodeRuntimeUpsert'
} as const;

export const NodesPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/NodePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'NodesPublic'
} as const;

export const PlatformRuntimePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        namespace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Namespace Id'
        },
        route_mode: {
            $ref: '#/components/schemas/RuntimeRouteMode'
        },
        model_id: {
            type: 'string',
            title: 'Model Id'
        },
        provider_config_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider Config Id'
        },
        base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Url'
        },
        permission_mode: {
            type: 'string',
            title: 'Permission Mode'
        },
        secret_masked: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secret Masked'
        },
        compatibility_verified: {
            type: 'boolean',
            title: 'Compatibility Verified'
        }
    },
    type: 'object',
    required: [
        'id',
        'namespace_id',
        'route_mode',
        'model_id',
        'provider_config_id',
        'base_url',
        'permission_mode',
        'secret_masked',
        'compatibility_verified'
    ],
    title: 'PlatformRuntimePublic'
} as const;

export const PlatformRuntimeUpsertSchema = {
    properties: {
        route_mode: {
            $ref: '#/components/schemas/RuntimeRouteMode'
        },
        model_id: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Model Id'
        },
        provider_config_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider Config Id'
        },
        base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Url'
        },
        permission_mode: {
            type: 'string',
            title: 'Permission Mode',
            default: 'default'
        },
        secret_inputs: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secret Inputs'
        }
    },
    type: 'object',
    required: [
        'route_mode',
        'model_id'
    ],
    title: 'PlatformRuntimeUpsert'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: [
        'email',
        'password',
        'full_name'
    ],
    title: 'PrivateUserCreate'
} as const;

export const ProviderAuthTypeSchema = {
    type: 'string',
    enum: [
        'api_key',
        'oauth_external',
        'oauth_device_code',
        'aws_sdk',
        'external_process',
        'copilot_token',
        'custom'
    ],
    title: 'ProviderAuthType'
} as const;

export const ProviderModelSourceTypeSchema = {
    type: 'string',
    enum: [
        'discovered',
        'manual'
    ],
    title: 'ProviderModelSourceType'
} as const;

export const ProviderModelSyncStatusSchema = {
    type: 'string',
    enum: [
        'active',
        'stale',
        'sync_failed'
    ],
    title: 'ProviderModelSyncStatus'
} as const;

export const ProviderValidationStatusSchema = {
    type: 'string',
    enum: [
        'unverified',
        'success',
        'failed',
        'unsupported'
    ],
    title: 'ProviderValidationStatus'
} as const;

export const ReleaseCreateSchema = {
    properties: {
        artifact_id: {
            type: 'string',
            format: 'uuid',
            title: 'Artifact Id'
        },
        node_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            minItems: 1,
            title: 'Node Ids'
        },
        valid_for_seconds: {
            type: 'integer',
            maximum: 86400,
            minimum: 60,
            title: 'Valid For Seconds',
            default: 3600
        }
    },
    type: 'object',
    required: [
        'artifact_id',
        'node_ids'
    ],
    title: 'ReleaseCreate'
} as const;

export const ReleasePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        artifact_id: {
            type: 'string',
            format: 'uuid',
            title: 'Artifact Id'
        },
        valid_until: {
            type: 'string',
            format: 'date-time',
            title: 'Valid Until'
        },
        rollback_of_release_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rollback Of Release Id'
        },
        deployments: {
            items: {
                $ref: '#/components/schemas/DeploymentPublic'
            },
            type: 'array',
            title: 'Deployments'
        }
    },
    type: 'object',
    required: [
        'id',
        'artifact_id',
        'valid_until',
        'rollback_of_release_id',
        'deployments'
    ],
    title: 'ReleasePublic'
} as const;

export const RuntimeRouteModeSchema = {
    type: 'string',
    enum: [
        'platform_gateway',
        'direct_anthropic'
    ],
    title: 'RuntimeRouteMode'
} as const;

export const SessionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        runtime_profile_id: {
            type: 'string',
            format: 'uuid',
            title: 'Runtime Profile Id'
        },
        sdk_session_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sdk Session Id'
        }
    },
    type: 'object',
    required: [
        'id',
        'runtime_profile_id',
        'sdk_session_id'
    ],
    title: 'SessionPublic'
} as const;

export const TaskCreateSchema = {
    properties: {
        runtime_profile_id: {
            type: 'string',
            format: 'uuid',
            title: 'Runtime Profile Id'
        },
        node_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Node Id'
        },
        prompt: {
            type: 'string',
            minLength: 1,
            title: 'Prompt'
        },
        task_kind: {
            $ref: '#/components/schemas/TaskKind',
            default: 'ordinary'
        },
        working_directory: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Working Directory'
        }
    },
    type: 'object',
    required: [
        'runtime_profile_id',
        'prompt'
    ],
    title: 'TaskCreate'
} as const;

export const TaskKindSchema = {
    type: 'string',
    enum: [
        'ordinary',
        'admin'
    ],
    title: 'TaskKind'
} as const;

export const TaskStatusSchema = {
    type: 'string',
    enum: [
        'queued',
        'dispatched',
        'running',
        'cancelling',
        'succeeded',
        'failed',
        'cancelled',
        'interrupted',
        'rejected'
    ],
    title: 'TaskStatus'
} as const;

export const TasksPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/app__api__routes__agent_tasks__TaskPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'TasksPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: [
        'access_token'
    ],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'current_password',
        'new_password'
    ],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'UserCreate'
} as const;

export const UserNamespaceAssignmentSchema = {
    properties: {
        namespace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Namespace Id'
        },
        role: {
            $ref: '#/components/schemas/NamespaceRole'
        }
    },
    type: 'object',
    required: [
        'namespace_id',
        'role'
    ],
    title: 'UserNamespaceAssignment'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        namespace_roles: {
            items: {
                $ref: '#/components/schemas/UserNamespaceAssignment'
            },
            type: 'array',
            title: 'Namespace Roles',
            default: []
        }
    },
    type: 'object',
    required: [
        'email',
        'id'
    ],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;

export const app__api__routes__agent_tasks__TaskPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        runtime_profile_id: {
            type: 'string',
            format: 'uuid',
            title: 'Runtime Profile Id'
        },
        node_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Node Id'
        },
        task_kind: {
            $ref: '#/components/schemas/TaskKind'
        },
        status: {
            $ref: '#/components/schemas/TaskStatus'
        },
        prompt: {
            type: 'string',
            title: 'Prompt'
        },
        snapshot: {
            additionalProperties: true,
            type: 'object',
            title: 'Snapshot'
        },
        final_result: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Final Result'
        },
        retry_of_task_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Retry Of Task Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'runtime_profile_id',
        'node_id',
        'task_kind',
        'status',
        'prompt',
        'snapshot',
        'final_result',
        'retry_of_task_id',
        'created_at',
        'updated_at'
    ],
    title: 'TaskPublic'
} as const;

export const app__api__routes__runtimes__TaskPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        session_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Session Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        }
    },
    type: 'object',
    required: [
        'id',
        'session_id',
        'status'
    ],
    title: 'TaskPublic'
} as const;
