// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AdminUserCreate
 */
export type AdminUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
    /**
     * Namespace Assignments
     */
    namespace_assignments?: Array<UserNamespaceAssignment>;
};

/**
 * AdminUserUpdate
 */
export type AdminUserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Namespace Assignments
     */
    namespace_assignments?: Array<UserNamespaceAssignment> | null;
};

/**
 * AgentEventType
 */
export type AgentEventType = 'user_message' | 'assistant_message' | 'tool_call' | 'tool_result' | 'status' | 'error' | 'result';

/**
 * ArtifactKind
 */
export type ArtifactKind = 'agent' | 'skill' | 'mcp' | 'cli_config' | 'workspace_content';

/**
 * ArtifactPublic
 */
export type ArtifactPublic = {
    /**
     * Id
     */
    id: string;
    kind: ArtifactKind;
    logical_target: LogicalTarget;
    /**
     * Version
     */
    version: string;
    /**
     * Content Sha256
     */
    content_sha256: string;
    /**
     * Size
     */
    size: number;
    /**
     * Manifest
     */
    manifest: {
        [key: string]: unknown;
    };
    /**
     * Signature
     */
    signature: string;
    /**
     * Signing Public Key
     */
    signing_public_key: string;
};

/**
 * ArtifactsPublic
 */
export type ArtifactsPublic = {
    /**
     * Data
     */
    data: Array<ArtifactPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_runtime-artifacts-upload_artifact
 */
export type BodyRuntimeArtifactsUploadArtifact = {
    kind: ArtifactKind;
    logical_target: LogicalTarget;
    /**
     * Version
     */
    version: string;
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ClaimInput
 */
export type ClaimInput = {
    /**
     * Worker Id
     */
    worker_id: string;
};

/**
 * DeploymentPublic
 */
export type DeploymentPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Artifact Id
     */
    artifact_id: string;
    /**
     * Previous Artifact Id
     */
    previous_artifact_id: string | null;
    /**
     * Attempt
     */
    attempt: number;
    status: DeploymentStatus;
    /**
     * Error
     */
    error: {
        [key: string]: unknown;
    } | null;
};

/**
 * DeploymentStatus
 */
export type DeploymentStatus = 'pending' | 'dispatched' | 'applied' | 'failed' | 'expired';

/**
 * EnrollmentTokenCreated
 */
export type EnrollmentTokenCreated = {
    /**
     * Id
     */
    id: string;
    /**
     * Token
     */
    token: string;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * EnrollmentTokenPublic
 */
export type EnrollmentTokenPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Expires At
     */
    expires_at: string;
    /**
     * Consumed At
     */
    consumed_at: string | null;
    /**
     * Revoked At
     */
    revoked_at: string | null;
};

/**
 * EnrollmentTokensPublic
 */
export type EnrollmentTokensPublic = {
    /**
     * Data
     */
    data: Array<EnrollmentTokenPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * EventBatch
 */
export type EventBatch = {
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Events
     */
    events: Array<EventInput>;
};

/**
 * EventInput
 */
export type EventInput = {
    /**
     * Sequence
     */
    sequence: number;
    event_type: AgentEventType;
    /**
     * Payload
     */
    payload: {
        [key: string]: unknown;
    };
};

/**
 * EventPublic
 */
export type EventPublic = {
    /**
     * Sequence
     */
    sequence: number;
    event_type: AgentEventType;
    /**
     * Payload
     */
    payload: {
        [key: string]: unknown;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * LeaseInput
 */
export type LeaseInput = {
    /**
     * Worker Id
     */
    worker_id: string;
    /**
     * Revision
     */
    revision: number;
};

/**
 * LlmProviderCatalogField
 */
export type LlmProviderCatalogField = {
    /**
     * Name
     */
    name: string;
    /**
     * Label
     */
    label: string;
    /**
     * Required
     */
    required?: boolean;
    /**
     * Placeholder
     */
    placeholder?: string | null;
    /**
     * Help Text
     */
    help_text?: string | null;
};

/**
 * LlmProviderCatalogItem
 */
export type LlmProviderCatalogItem = {
    /**
     * Provider Slug
     */
    provider_slug: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Description
     */
    description?: string | null;
    auth_type: ProviderAuthType;
    /**
     * Default Base Url
     */
    default_base_url?: string | null;
    /**
     * Supports Health Check
     */
    supports_health_check: boolean;
    /**
     * Supports Model Discovery
     */
    supports_model_discovery: boolean;
    /**
     * Base Url Editable
     */
    base_url_editable: boolean;
    /**
     * Secret Fields
     */
    secret_fields?: Array<LlmProviderCatalogField>;
    /**
     * Extra Fields
     */
    extra_fields?: Array<LlmProviderCatalogField>;
};

/**
 * LlmProviderCatalogPublic
 */
export type LlmProviderCatalogPublic = {
    /**
     * Data
     */
    data: Array<LlmProviderCatalogItem>;
    /**
     * Count
     */
    count: number;
};

/**
 * LlmProviderConfigCreate
 */
export type LlmProviderConfigCreate = {
    /**
     * Config Name
     */
    config_name: string;
    /**
     * Provider Slug
     */
    provider_slug: string;
    /**
     * Base Url
     */
    base_url: string;
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Extra Config
     */
    extra_config?: {
        [key: string]: unknown;
    };
    /**
     * Secret Inputs
     */
    secret_inputs?: {
        [key: string]: string;
    };
    /**
     * Manual Models
     */
    manual_models?: Array<LlmProviderModelInput>;
    /**
     * Enabled Model Ids
     */
    enabled_model_ids?: Array<string>;
};

/**
 * LlmProviderConfigPublic
 */
export type LlmProviderConfigPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Namespace Id
     */
    namespace_id: string;
    /**
     * Config Name
     */
    config_name: string;
    /**
     * Provider Slug
     */
    provider_slug: string;
    /**
     * Provider Display Name
     */
    provider_display_name: string;
    auth_type: ProviderAuthType;
    /**
     * Base Url
     */
    base_url: string;
    /**
     * Secret Masked
     */
    secret_masked?: string | null;
    /**
     * Extra Config
     */
    extra_config?: {
        [key: string]: unknown;
    };
    /**
     * Supports Health Check
     */
    supports_health_check: boolean;
    /**
     * Supports Model Discovery
     */
    supports_model_discovery: boolean;
    validation_status: ProviderValidationStatus;
    /**
     * Validation Message
     */
    validation_message?: string | null;
    /**
     * Last Validated At
     */
    last_validated_at?: string | null;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Models
     */
    models?: Array<LlmProviderModelPublic>;
};

/**
 * LlmProviderConfigUpdate
 */
export type LlmProviderConfigUpdate = {
    /**
     * Config Name
     */
    config_name?: string | null;
    /**
     * Base Url
     */
    base_url?: string | null;
    /**
     * Enabled
     */
    enabled?: boolean | null;
    /**
     * Secret Inputs
     */
    secret_inputs?: {
        [key: string]: string;
    } | null;
    /**
     * Extra Config
     */
    extra_config?: {
        [key: string]: unknown;
    } | null;
    /**
     * Manual Models
     */
    manual_models?: Array<LlmProviderModelInput> | null;
    /**
     * Enabled Model Ids
     */
    enabled_model_ids?: Array<string> | null;
};

/**
 * LlmProviderConfigsPublic
 */
export type LlmProviderConfigsPublic = {
    /**
     * Data
     */
    data: Array<LlmProviderConfigPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * LlmProviderModelInput
 */
export type LlmProviderModelInput = {
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Display Name
     */
    display_name?: string | null;
};

/**
 * LlmProviderModelPublic
 */
export type LlmProviderModelPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Display Name
     */
    display_name?: string | null;
    source_type: ProviderModelSourceType;
    /**
     * Is Enabled
     */
    is_enabled: boolean;
    sync_status: ProviderModelSyncStatus;
    /**
     * Raw Metadata
     */
    raw_metadata?: {
        [key: string]: unknown;
    };
    /**
     * Last Synced At
     */
    last_synced_at?: string | null;
};

/**
 * LlmProviderSyncModelsRequest
 */
export type LlmProviderSyncModelsRequest = {
    /**
     * Manual Models
     */
    manual_models?: Array<LlmProviderModelInput>;
    /**
     * Enabled Model Ids
     */
    enabled_model_ids?: Array<string>;
};

/**
 * LogicalTarget
 */
export type LogicalTarget = 'agents' | 'skills' | 'mcp' | 'cli' | 'workspace';

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * MessageInput
 */
export type MessageInput = {
    /**
     * Prompt
     */
    prompt: string;
};

/**
 * NamespaceCreate
 */
export type NamespaceCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Admin User Id
     */
    admin_user_id?: string | null;
};

/**
 * NamespacePublic
 */
export type NamespacePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * NamespaceRole
 */
export type NamespaceRole = 'admin' | 'developer' | 'user';

/**
 * NamespaceUpdate
 */
export type NamespaceUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Code
     */
    code?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Admin User Id
     */
    admin_user_id?: string | null;
};

/**
 * NamespaceUserCreate
 */
export type NamespaceUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    role?: NamespaceRole;
};

/**
 * NamespaceUserUpdate
 */
export type NamespaceUserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    role?: NamespaceRole | null;
};

/**
 * NamespacesPublic
 */
export type NamespacesPublic = {
    /**
     * Data
     */
    data: Array<NamespacePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * NodeEnrollInput
 */
export type NodeEnrollInput = {
    /**
     * Token
     */
    token: string;
    /**
     * Name
     */
    name: string;
    /**
     * Hostname
     */
    hostname: string;
    /**
     * Os Name
     */
    os_name: string;
    /**
     * Architecture
     */
    architecture: string;
    /**
     * Agent Version
     */
    agent_version: string;
    /**
     * Sdk Version
     */
    sdk_version?: string | null;
    /**
     * Public Key
     */
    public_key: string;
};

/**
 * NodeEnrollResult
 */
export type NodeEnrollResult = {
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Namespace Id
     */
    namespace_id: string;
    /**
     * Credential
     */
    credential: string;
    /**
     * Credential Expires At
     */
    credential_expires_at: string;
};

/**
 * NodePublic
 */
export type NodePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Hostname
     */
    hostname: string;
    /**
     * Os Name
     */
    os_name: string;
    /**
     * Architecture
     */
    architecture: string;
    /**
     * Agent Version
     */
    agent_version: string;
    /**
     * Sdk Version
     */
    sdk_version: string | null;
    /**
     * Online
     */
    online: boolean;
    /**
     * Last Seen At
     */
    last_seen_at: string | null;
    /**
     * Revoked At
     */
    revoked_at: string | null;
    /**
     * Runtime Profile Id
     */
    runtime_profile_id: string | null;
};

/**
 * NodeRuntimePublic
 */
export type NodeRuntimePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Node Id
     */
    node_id: string;
    route_mode: RuntimeRouteMode;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Provider Config Id
     */
    provider_config_id: string | null;
    /**
     * Base Url
     */
    base_url: string | null;
    permission_mode: PermissionMode;
    /**
     * Secret Masked
     */
    secret_masked: string | null;
};

/**
 * NodeRuntimeUpsert
 */
export type NodeRuntimeUpsert = {
    route_mode: RuntimeRouteMode;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Provider Config Id
     */
    provider_config_id?: string | null;
    /**
     * Base Url
     */
    base_url?: string | null;
    permission_mode?: PermissionMode;
    /**
     * Secret Inputs
     */
    secret_inputs?: {
        [key: string]: string;
    } | null;
};

/**
 * NodesPublic
 */
export type NodesPublic = {
    /**
     * Data
     */
    data: Array<NodePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PermissionMode
 */
export type PermissionMode = 'default' | 'acceptEdits' | 'plan' | 'dontAsk';

/**
 * PlatformRuntimePublic
 */
export type PlatformRuntimePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Namespace Id
     */
    namespace_id: string;
    route_mode: RuntimeRouteMode;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Provider Config Id
     */
    provider_config_id: string | null;
    /**
     * Base Url
     */
    base_url: string | null;
    permission_mode: PermissionMode;
    /**
     * Secret Masked
     */
    secret_masked: string | null;
    /**
     * Compatibility Verified
     */
    compatibility_verified: boolean;
};

/**
 * PlatformRuntimeUpsert
 */
export type PlatformRuntimeUpsert = {
    route_mode: RuntimeRouteMode;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Provider Config Id
     */
    provider_config_id?: string | null;
    /**
     * Base Url
     */
    base_url?: string | null;
    permission_mode?: PermissionMode;
    /**
     * Secret Inputs
     */
    secret_inputs?: {
        [key: string]: string;
    } | null;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * ProviderAuthType
 */
export type ProviderAuthType = 'api_key' | 'oauth_external' | 'oauth_device_code' | 'aws_sdk' | 'external_process' | 'copilot_token' | 'custom';

/**
 * ProviderModelSourceType
 */
export type ProviderModelSourceType = 'discovered' | 'manual';

/**
 * ProviderModelSyncStatus
 */
export type ProviderModelSyncStatus = 'active' | 'stale' | 'sync_failed';

/**
 * ProviderValidationStatus
 */
export type ProviderValidationStatus = 'unverified' | 'success' | 'failed' | 'unsupported';

/**
 * ReleaseCreate
 */
export type ReleaseCreate = {
    /**
     * Artifact Id
     */
    artifact_id: string;
    /**
     * Node Ids
     */
    node_ids: Array<string>;
    /**
     * Valid For Seconds
     */
    valid_for_seconds?: number;
};

/**
 * ReleasePublic
 */
export type ReleasePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Artifact Id
     */
    artifact_id: string;
    /**
     * Valid Until
     */
    valid_until: string;
    /**
     * Rollback Of Release Id
     */
    rollback_of_release_id: string | null;
    /**
     * Deployments
     */
    deployments: Array<DeploymentPublic>;
};

/**
 * RuntimeRouteMode
 */
export type RuntimeRouteMode = 'platform_gateway' | 'direct_anthropic';

/**
 * SessionPublic
 */
export type SessionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Runtime Profile Id
     */
    runtime_profile_id: string;
    /**
     * Sdk Session Id
     */
    sdk_session_id: string | null;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
    /**
     * Runtime Profile Id
     */
    runtime_profile_id: string;
    /**
     * Node Id
     */
    node_id?: string | null;
    /**
     * Prompt
     */
    prompt: string;
    task_kind?: TaskKind;
    /**
     * Working Directory
     */
    working_directory?: string | null;
};

/**
 * TaskKind
 */
export type TaskKind = 'ordinary' | 'admin';

/**
 * TaskStatus
 */
export type TaskStatus = 'queued' | 'dispatched' | 'running' | 'cancelling' | 'succeeded' | 'failed' | 'cancelled' | 'interrupted' | 'rejected';

/**
 * TasksPublic
 */
export type TasksPublic = {
    /**
     * Data
     */
    data: Array<AppApiRoutesAgentTasksTaskPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserNamespaceAssignment
 */
export type UserNamespaceAssignment = {
    /**
     * Namespace Id
     */
    namespace_id: string;
    role: NamespaceRole;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Namespace Roles
     */
    namespace_roles?: Array<UserNamespaceAssignment>;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * TaskPublic
 */
export type AppApiRoutesAgentTasksTaskPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Runtime Profile Id
     */
    runtime_profile_id: string;
    /**
     * Node Id
     */
    node_id: string | null;
    task_kind: TaskKind;
    status: TaskStatus;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Snapshot
     */
    snapshot: {
        [key: string]: unknown;
    };
    /**
     * Final Result
     */
    final_result: {
        [key: string]: unknown;
    } | null;
    /**
     * Retry Of Task Id
     */
    retry_of_task_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * TaskPublic
 */
export type AppApiRoutesRuntimesTaskPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Session Id
     */
    session_id: string | null;
    /**
     * Status
     */
    status: string;
};

export type RuntimeTasksListTasksData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtime-tasks';
};

export type RuntimeTasksListTasksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeTasksListTasksError = RuntimeTasksListTasksErrors[keyof RuntimeTasksListTasksErrors];

export type RuntimeTasksListTasksResponses = {
    /**
     * Successful Response
     */
    200: TasksPublic;
};

export type RuntimeTasksListTasksResponse = RuntimeTasksListTasksResponses[keyof RuntimeTasksListTasksResponses];

export type RuntimeTasksCreateTaskData = {
    body: TaskCreate;
    headers?: {
        /**
         * Idempotency-Key
         */
        'Idempotency-Key'?: string | null;
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtime-tasks';
};

export type RuntimeTasksCreateTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeTasksCreateTaskError = RuntimeTasksCreateTaskErrors[keyof RuntimeTasksCreateTaskErrors];

export type RuntimeTasksCreateTaskResponses = {
    /**
     * Successful Response
     */
    202: AppApiRoutesAgentTasksTaskPublic;
};

export type RuntimeTasksCreateTaskResponse = RuntimeTasksCreateTaskResponses[keyof RuntimeTasksCreateTaskResponses];

export type RuntimeTasksReadTaskData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtime-tasks/{task_id}';
};

export type RuntimeTasksReadTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeTasksReadTaskError = RuntimeTasksReadTaskErrors[keyof RuntimeTasksReadTaskErrors];

export type RuntimeTasksReadTaskResponses = {
    /**
     * Successful Response
     */
    200: AppApiRoutesAgentTasksTaskPublic;
};

export type RuntimeTasksReadTaskResponse = RuntimeTasksReadTaskResponses[keyof RuntimeTasksReadTaskResponses];

export type RuntimeTasksCancelTaskData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtime-tasks/{task_id}/cancel';
};

export type RuntimeTasksCancelTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeTasksCancelTaskError = RuntimeTasksCancelTaskErrors[keyof RuntimeTasksCancelTaskErrors];

export type RuntimeTasksCancelTaskResponses = {
    /**
     * Successful Response
     */
    200: AppApiRoutesAgentTasksTaskPublic;
};

export type RuntimeTasksCancelTaskResponse = RuntimeTasksCancelTaskResponses[keyof RuntimeTasksCancelTaskResponses];

export type RuntimeTasksRetryFailedTaskData = {
    body?: never;
    headers?: {
        /**
         * Idempotency-Key
         */
        'Idempotency-Key'?: string | null;
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtime-tasks/{task_id}/retry';
};

export type RuntimeTasksRetryFailedTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeTasksRetryFailedTaskError = RuntimeTasksRetryFailedTaskErrors[keyof RuntimeTasksRetryFailedTaskErrors];

export type RuntimeTasksRetryFailedTaskResponses = {
    /**
     * Successful Response
     */
    202: AppApiRoutesAgentTasksTaskPublic;
};

export type RuntimeTasksRetryFailedTaskResponse = RuntimeTasksRetryFailedTaskResponses[keyof RuntimeTasksRetryFailedTaskResponses];

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginRefreshAccessTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/refresh';
};

export type LoginRefreshAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRefreshAccessTokenError = LoginRefreshAccessTokenErrors[keyof LoginRefreshAccessTokenErrors];

export type LoginRefreshAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginRefreshAccessTokenResponse = LoginRefreshAccessTokenResponses[keyof LoginRefreshAccessTokenResponses];

export type LoginLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/logout';
};

export type LoginLogoutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLogoutError = LoginLogoutErrors[keyof LoginLogoutErrors];

export type LoginLogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LoginLogoutResponse = LoginLogoutResponses[keyof LoginLogoutResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginTestTokenError = LoginTestTokenErrors[keyof LoginTestTokenErrors];

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type LoginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type LoginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type LoginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type LoginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordHtmlContentError = LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors];

export type LoginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type LoginRecoverPasswordHtmlContentResponse = LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserMeError = UsersDeleteUserMeErrors[keyof UsersDeleteUserMeErrors];

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserMeError = UsersReadUserMeErrors[keyof UsersReadUserMeErrors];

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UtilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type UtilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UtilsTestEmailError = UtilsTestEmailErrors[keyof UtilsTestEmailErrors];

export type UtilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type UtilsTestEmailResponse = UtilsTestEmailResponses[keyof UtilsTestEmailResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type ItemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type ItemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemsError = ItemsReadItemsErrors[keyof ItemsReadItemsErrors];

export type ItemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type ItemsReadItemsResponse = ItemsReadItemsResponses[keyof ItemsReadItemsResponses];

export type ItemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type ItemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsCreateItemError = ItemsCreateItemErrors[keyof ItemsCreateItemErrors];

export type ItemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsCreateItemResponse = ItemsCreateItemResponses[keyof ItemsCreateItemResponses];

export type ItemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsDeleteItemError = ItemsDeleteItemErrors[keyof ItemsDeleteItemErrors];

export type ItemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ItemsDeleteItemResponse = ItemsDeleteItemResponses[keyof ItemsDeleteItemResponses];

export type ItemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemError = ItemsReadItemErrors[keyof ItemsReadItemErrors];

export type ItemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsReadItemResponse = ItemsReadItemResponses[keyof ItemsReadItemResponses];

export type ItemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsUpdateItemError = ItemsUpdateItemErrors[keyof ItemsUpdateItemErrors];

export type ItemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsUpdateItemResponse = ItemsUpdateItemResponses[keyof ItemsUpdateItemResponses];

export type NamespacesReadMyNamespacesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/namespaces/mine';
};

export type NamespacesReadMyNamespacesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NamespacesReadMyNamespacesError = NamespacesReadMyNamespacesErrors[keyof NamespacesReadMyNamespacesErrors];

export type NamespacesReadMyNamespacesResponses = {
    /**
     * Successful Response
     */
    200: NamespacesPublic;
};

export type NamespacesReadMyNamespacesResponse = NamespacesReadMyNamespacesResponses[keyof NamespacesReadMyNamespacesResponses];

export type NamespacesReadNamespaceUsersData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Namespace Id
         */
        namespace_id: string | null;
    };
    query?: never;
    url: '/api/v1/namespaces/{namespace_id}/users';
};

export type NamespacesReadNamespaceUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NamespacesReadNamespaceUsersError = NamespacesReadNamespaceUsersErrors[keyof NamespacesReadNamespaceUsersErrors];

export type NamespacesReadNamespaceUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type NamespacesReadNamespaceUsersResponse = NamespacesReadNamespaceUsersResponses[keyof NamespacesReadNamespaceUsersResponses];

export type NamespacesCreateNamespaceUserData = {
    body: NamespaceUserCreate;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Namespace Id
         */
        namespace_id: string | null;
    };
    query?: never;
    url: '/api/v1/namespaces/{namespace_id}/users';
};

export type NamespacesCreateNamespaceUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NamespacesCreateNamespaceUserError = NamespacesCreateNamespaceUserErrors[keyof NamespacesCreateNamespaceUserErrors];

export type NamespacesCreateNamespaceUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type NamespacesCreateNamespaceUserResponse = NamespacesCreateNamespaceUserResponses[keyof NamespacesCreateNamespaceUserResponses];

export type NamespacesDeleteNamespaceUserData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Namespace Id
         */
        namespace_id: string | null;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/namespaces/{namespace_id}/users/{user_id}';
};

export type NamespacesDeleteNamespaceUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NamespacesDeleteNamespaceUserError = NamespacesDeleteNamespaceUserErrors[keyof NamespacesDeleteNamespaceUserErrors];

export type NamespacesDeleteNamespaceUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type NamespacesDeleteNamespaceUserResponse = NamespacesDeleteNamespaceUserResponses[keyof NamespacesDeleteNamespaceUserResponses];

export type NamespacesUpdateNamespaceUserData = {
    body: NamespaceUserUpdate;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Namespace Id
         */
        namespace_id: string | null;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/namespaces/{namespace_id}/users/{user_id}';
};

export type NamespacesUpdateNamespaceUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NamespacesUpdateNamespaceUserError = NamespacesUpdateNamespaceUserErrors[keyof NamespacesUpdateNamespaceUserErrors];

export type NamespacesUpdateNamespaceUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type NamespacesUpdateNamespaceUserResponse = NamespacesUpdateNamespaceUserResponses[keyof NamespacesUpdateNamespaceUserResponses];

export type PlatformReadNamespacesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/platform/namespaces';
};

export type PlatformReadNamespacesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PlatformReadNamespacesError = PlatformReadNamespacesErrors[keyof PlatformReadNamespacesErrors];

export type PlatformReadNamespacesResponses = {
    /**
     * Successful Response
     */
    200: NamespacesPublic;
};

export type PlatformReadNamespacesResponse = PlatformReadNamespacesResponses[keyof PlatformReadNamespacesResponses];

export type PlatformCreateNamespaceData = {
    body: NamespaceCreate;
    path?: never;
    query?: never;
    url: '/api/v1/platform/namespaces';
};

export type PlatformCreateNamespaceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PlatformCreateNamespaceError = PlatformCreateNamespaceErrors[keyof PlatformCreateNamespaceErrors];

export type PlatformCreateNamespaceResponses = {
    /**
     * Successful Response
     */
    200: NamespacePublic;
};

export type PlatformCreateNamespaceResponse = PlatformCreateNamespaceResponses[keyof PlatformCreateNamespaceResponses];

export type PlatformDeleteNamespaceData = {
    body?: never;
    path: {
        /**
         * Namespace Id
         */
        namespace_id: string;
    };
    query?: never;
    url: '/api/v1/platform/namespaces/{namespace_id}';
};

export type PlatformDeleteNamespaceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PlatformDeleteNamespaceError = PlatformDeleteNamespaceErrors[keyof PlatformDeleteNamespaceErrors];

export type PlatformDeleteNamespaceResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PlatformDeleteNamespaceResponse = PlatformDeleteNamespaceResponses[keyof PlatformDeleteNamespaceResponses];

export type PlatformUpdateNamespaceData = {
    body: NamespaceUpdate;
    path: {
        /**
         * Namespace Id
         */
        namespace_id: string;
    };
    query?: never;
    url: '/api/v1/platform/namespaces/{namespace_id}';
};

export type PlatformUpdateNamespaceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PlatformUpdateNamespaceError = PlatformUpdateNamespaceErrors[keyof PlatformUpdateNamespaceErrors];

export type PlatformUpdateNamespaceResponses = {
    /**
     * Successful Response
     */
    200: NamespacePublic;
};

export type PlatformUpdateNamespaceResponse = PlatformUpdateNamespaceResponses[keyof PlatformUpdateNamespaceResponses];

export type PlatformReadPlatformUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/platform/users';
};

export type PlatformReadPlatformUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PlatformReadPlatformUsersError = PlatformReadPlatformUsersErrors[keyof PlatformReadPlatformUsersErrors];

export type PlatformReadPlatformUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type PlatformReadPlatformUsersResponse = PlatformReadPlatformUsersResponses[keyof PlatformReadPlatformUsersResponses];

export type PlatformCreatePlatformUserData = {
    body: AdminUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/platform/users';
};

export type PlatformCreatePlatformUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PlatformCreatePlatformUserError = PlatformCreatePlatformUserErrors[keyof PlatformCreatePlatformUserErrors];

export type PlatformCreatePlatformUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PlatformCreatePlatformUserResponse = PlatformCreatePlatformUserResponses[keyof PlatformCreatePlatformUserResponses];

export type PlatformDeletePlatformUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/platform/users/{user_id}';
};

export type PlatformDeletePlatformUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PlatformDeletePlatformUserError = PlatformDeletePlatformUserErrors[keyof PlatformDeletePlatformUserErrors];

export type PlatformDeletePlatformUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PlatformDeletePlatformUserResponse = PlatformDeletePlatformUserResponses[keyof PlatformDeletePlatformUserResponses];

export type PlatformUpdatePlatformUserData = {
    body: AdminUserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/platform/users/{user_id}';
};

export type PlatformUpdatePlatformUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PlatformUpdatePlatformUserError = PlatformUpdatePlatformUserErrors[keyof PlatformUpdatePlatformUserErrors];

export type PlatformUpdatePlatformUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PlatformUpdatePlatformUserResponse = PlatformUpdatePlatformUserResponses[keyof PlatformUpdatePlatformUserResponses];

export type LlmReadProviderCatalogData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/llm/providers/catalog';
};

export type LlmReadProviderCatalogErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LlmReadProviderCatalogError = LlmReadProviderCatalogErrors[keyof LlmReadProviderCatalogErrors];

export type LlmReadProviderCatalogResponses = {
    /**
     * Successful Response
     */
    200: LlmProviderCatalogPublic;
};

export type LlmReadProviderCatalogResponse = LlmReadProviderCatalogResponses[keyof LlmReadProviderCatalogResponses];

export type LlmReadProviderConfigsData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/llm/provider-configs';
};

export type LlmReadProviderConfigsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LlmReadProviderConfigsError = LlmReadProviderConfigsErrors[keyof LlmReadProviderConfigsErrors];

export type LlmReadProviderConfigsResponses = {
    /**
     * Successful Response
     */
    200: LlmProviderConfigsPublic;
};

export type LlmReadProviderConfigsResponse = LlmReadProviderConfigsResponses[keyof LlmReadProviderConfigsResponses];

export type LlmCreateProviderConfigData = {
    body: LlmProviderConfigCreate;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/llm/provider-configs';
};

export type LlmCreateProviderConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LlmCreateProviderConfigError = LlmCreateProviderConfigErrors[keyof LlmCreateProviderConfigErrors];

export type LlmCreateProviderConfigResponses = {
    /**
     * Successful Response
     */
    200: LlmProviderConfigPublic;
};

export type LlmCreateProviderConfigResponse = LlmCreateProviderConfigResponses[keyof LlmCreateProviderConfigResponses];

export type LlmUpdateProviderConfigData = {
    body: LlmProviderConfigUpdate;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Config Id
         */
        config_id: string;
    };
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/llm/provider-configs/{config_id}';
};

export type LlmUpdateProviderConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LlmUpdateProviderConfigError = LlmUpdateProviderConfigErrors[keyof LlmUpdateProviderConfigErrors];

export type LlmUpdateProviderConfigResponses = {
    /**
     * Successful Response
     */
    200: LlmProviderConfigPublic;
};

export type LlmUpdateProviderConfigResponse = LlmUpdateProviderConfigResponses[keyof LlmUpdateProviderConfigResponses];

export type LlmValidateProviderConfigData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Config Id
         */
        config_id: string;
    };
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/llm/provider-configs/{config_id}/validate';
};

export type LlmValidateProviderConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LlmValidateProviderConfigError = LlmValidateProviderConfigErrors[keyof LlmValidateProviderConfigErrors];

export type LlmValidateProviderConfigResponses = {
    /**
     * Successful Response
     */
    200: LlmProviderConfigPublic;
};

export type LlmValidateProviderConfigResponse = LlmValidateProviderConfigResponses[keyof LlmValidateProviderConfigResponses];

export type LlmSyncProviderModelsData = {
    body: LlmProviderSyncModelsRequest;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Config Id
         */
        config_id: string;
    };
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/llm/provider-configs/{config_id}/sync-models';
};

export type LlmSyncProviderModelsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LlmSyncProviderModelsError = LlmSyncProviderModelsErrors[keyof LlmSyncProviderModelsErrors];

export type LlmSyncProviderModelsResponses = {
    /**
     * Successful Response
     */
    200: LlmProviderConfigPublic;
};

export type LlmSyncProviderModelsResponse = LlmSyncProviderModelsResponses[keyof LlmSyncProviderModelsResponses];

export type RuntimesReadPlatformRuntimeData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtimes/platform';
};

export type RuntimesReadPlatformRuntimeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimesReadPlatformRuntimeError = RuntimesReadPlatformRuntimeErrors[keyof RuntimesReadPlatformRuntimeErrors];

export type RuntimesReadPlatformRuntimeResponses = {
    /**
     * Successful Response
     */
    200: PlatformRuntimePublic;
};

export type RuntimesReadPlatformRuntimeResponse = RuntimesReadPlatformRuntimeResponses[keyof RuntimesReadPlatformRuntimeResponses];

export type RuntimesUpsertPlatformRuntimeData = {
    body: PlatformRuntimeUpsert;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtimes/platform';
};

export type RuntimesUpsertPlatformRuntimeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimesUpsertPlatformRuntimeError = RuntimesUpsertPlatformRuntimeErrors[keyof RuntimesUpsertPlatformRuntimeErrors];

export type RuntimesUpsertPlatformRuntimeResponses = {
    /**
     * Successful Response
     */
    200: PlatformRuntimePublic;
};

export type RuntimesUpsertPlatformRuntimeResponse = RuntimesUpsertPlatformRuntimeResponses[keyof RuntimesUpsertPlatformRuntimeResponses];

export type RuntimesValidatePlatformRuntimeData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtimes/platform/validate';
};

export type RuntimesValidatePlatformRuntimeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimesValidatePlatformRuntimeError = RuntimesValidatePlatformRuntimeErrors[keyof RuntimesValidatePlatformRuntimeErrors];

export type RuntimesValidatePlatformRuntimeResponses = {
    /**
     * Successful Response
     */
    200: PlatformRuntimePublic;
};

export type RuntimesValidatePlatformRuntimeResponse = RuntimesValidatePlatformRuntimeResponses[keyof RuntimesValidatePlatformRuntimeResponses];

export type RuntimesCreatePlatformSessionData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtimes/platform/sessions';
};

export type RuntimesCreatePlatformSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimesCreatePlatformSessionError = RuntimesCreatePlatformSessionErrors[keyof RuntimesCreatePlatformSessionErrors];

export type RuntimesCreatePlatformSessionResponses = {
    /**
     * Successful Response
     */
    201: SessionPublic;
};

export type RuntimesCreatePlatformSessionResponse = RuntimesCreatePlatformSessionResponses[keyof RuntimesCreatePlatformSessionResponses];

export type RuntimesCreateSessionMessageData = {
    body: MessageInput;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtimes/sessions/{session_id}/messages';
};

export type RuntimesCreateSessionMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimesCreateSessionMessageError = RuntimesCreateSessionMessageErrors[keyof RuntimesCreateSessionMessageErrors];

export type RuntimesCreateSessionMessageResponses = {
    /**
     * Successful Response
     */
    202: AppApiRoutesRuntimesTaskPublic;
};

export type RuntimesCreateSessionMessageResponse = RuntimesCreateSessionMessageResponses[keyof RuntimesCreateSessionMessageResponses];

export type RuntimesReadTaskData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtimes/tasks/{task_id}';
};

export type RuntimesReadTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimesReadTaskError = RuntimesReadTaskErrors[keyof RuntimesReadTaskErrors];

export type RuntimesReadTaskResponses = {
    /**
     * Successful Response
     */
    200: AppApiRoutesRuntimesTaskPublic;
};

export type RuntimesReadTaskResponse = RuntimesReadTaskResponses[keyof RuntimesReadTaskResponses];

export type RuntimesReadTaskEventsData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: {
        /**
         * After Sequence
         */
        after_sequence?: number;
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtimes/tasks/{task_id}/events';
};

export type RuntimesReadTaskEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimesReadTaskEventsError = RuntimesReadTaskEventsErrors[keyof RuntimesReadTaskEventsErrors];

export type RuntimesReadTaskEventsResponses = {
    /**
     * Response Runtimes-Read Task Events
     *
     * Successful Response
     */
    200: Array<EventPublic>;
};

export type RuntimesReadTaskEventsResponse = RuntimesReadTaskEventsResponses[keyof RuntimesReadTaskEventsResponses];

export type RuntimesStreamTaskEventsData = {
    body?: never;
    headers?: {
        /**
         * Last-Event-Id
         */
        'Last-Event-ID'?: string | null;
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: {
        /**
         * After Sequence
         */
        after_sequence?: number;
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtimes/tasks/{task_id}/stream';
};

export type RuntimesStreamTaskEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimesStreamTaskEventsError = RuntimesStreamTaskEventsErrors[keyof RuntimesStreamTaskEventsErrors];

export type RuntimesStreamTaskEventsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RuntimesCancelTaskData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtimes/tasks/{task_id}/cancel';
};

export type RuntimesCancelTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimesCancelTaskError = RuntimesCancelTaskErrors[keyof RuntimesCancelTaskErrors];

export type RuntimesCancelTaskResponses = {
    /**
     * Successful Response
     */
    200: AppApiRoutesRuntimesTaskPublic;
};

export type RuntimesCancelTaskResponse = RuntimesCancelTaskResponses[keyof RuntimesCancelTaskResponses];

export type RuntimeInternalSigningProbeData = {
    body?: never;
    headers?: {
        /**
         * X-Runtime-Token
         */
        'X-Runtime-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/internal/runtime/signing-probe';
};

export type RuntimeInternalSigningProbeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeInternalSigningProbeError = RuntimeInternalSigningProbeErrors[keyof RuntimeInternalSigningProbeErrors];

export type RuntimeInternalSigningProbeResponses = {
    /**
     * Response Runtime-Internal-Signing Probe
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type RuntimeInternalSigningProbeResponse = RuntimeInternalSigningProbeResponses[keyof RuntimeInternalSigningProbeResponses];

export type RuntimeInternalAppendEventsData = {
    body: EventBatch;
    headers?: {
        /**
         * X-Runtime-Token
         */
        'X-Runtime-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/internal/runtime/events';
};

export type RuntimeInternalAppendEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeInternalAppendEventsError = RuntimeInternalAppendEventsErrors[keyof RuntimeInternalAppendEventsErrors];

export type RuntimeInternalAppendEventsResponses = {
    /**
     * Response Runtime-Internal-Append Events
     *
     * Successful Response
     */
    200: {
        [key: string]: number;
    };
};

export type RuntimeInternalAppendEventsResponse = RuntimeInternalAppendEventsResponses[keyof RuntimeInternalAppendEventsResponses];

export type RuntimeInternalClaimPlatformTaskData = {
    body: ClaimInput;
    headers?: {
        /**
         * X-Runtime-Token
         */
        'X-Runtime-Token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/internal/runtime/tasks/claim';
};

export type RuntimeInternalClaimPlatformTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeInternalClaimPlatformTaskError = RuntimeInternalClaimPlatformTaskErrors[keyof RuntimeInternalClaimPlatformTaskErrors];

export type RuntimeInternalClaimPlatformTaskResponses = {
    /**
     * Response Runtime-Internal-Claim Platform Task
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type RuntimeInternalClaimPlatformTaskResponse = RuntimeInternalClaimPlatformTaskResponses[keyof RuntimeInternalClaimPlatformTaskResponses];

export type RuntimeInternalRenewPlatformTaskLeaseData = {
    body: LeaseInput;
    headers?: {
        /**
         * X-Runtime-Token
         */
        'X-Runtime-Token'?: string | null;
    };
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/internal/runtime/tasks/{task_id}/lease';
};

export type RuntimeInternalRenewPlatformTaskLeaseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeInternalRenewPlatformTaskLeaseError = RuntimeInternalRenewPlatformTaskLeaseErrors[keyof RuntimeInternalRenewPlatformTaskLeaseErrors];

export type RuntimeInternalRenewPlatformTaskLeaseResponses = {
    /**
     * Response Runtime-Internal-Renew Platform Task Lease
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type RuntimeInternalRenewPlatformTaskLeaseResponse = RuntimeInternalRenewPlatformTaskLeaseResponses[keyof RuntimeInternalRenewPlatformTaskLeaseResponses];

export type RuntimeInternalResolveRouteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
        /**
         * X-Runtime-Token
         */
        'X-Runtime-Token'?: string | null;
    };
    path: {
        /**
         * Runtime Id
         */
        runtime_id: string;
        /**
         * Task Id
         */
        task_id: string;
    };
    query: {
        /**
         * Model Id
         */
        model_id: string;
    };
    url: '/api/v1/internal/runtime/routes/{runtime_id}/tasks/{task_id}';
};

export type RuntimeInternalResolveRouteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeInternalResolveRouteError = RuntimeInternalResolveRouteErrors[keyof RuntimeInternalResolveRouteErrors];

export type RuntimeInternalResolveRouteResponses = {
    /**
     * Response Runtime-Internal-Resolve Route
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type RuntimeInternalResolveRouteResponse = RuntimeInternalResolveRouteResponses[keyof RuntimeInternalResolveRouteResponses];

export type RuntimeArtifactsListArtifactsData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtime-artifacts';
};

export type RuntimeArtifactsListArtifactsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeArtifactsListArtifactsError = RuntimeArtifactsListArtifactsErrors[keyof RuntimeArtifactsListArtifactsErrors];

export type RuntimeArtifactsListArtifactsResponses = {
    /**
     * Successful Response
     */
    200: ArtifactsPublic;
};

export type RuntimeArtifactsListArtifactsResponse = RuntimeArtifactsListArtifactsResponses[keyof RuntimeArtifactsListArtifactsResponses];

export type RuntimeArtifactsUploadArtifactData = {
    body: BodyRuntimeArtifactsUploadArtifact;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtime-artifacts';
};

export type RuntimeArtifactsUploadArtifactErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeArtifactsUploadArtifactError = RuntimeArtifactsUploadArtifactErrors[keyof RuntimeArtifactsUploadArtifactErrors];

export type RuntimeArtifactsUploadArtifactResponses = {
    /**
     * Successful Response
     */
    201: ArtifactPublic;
};

export type RuntimeArtifactsUploadArtifactResponse = RuntimeArtifactsUploadArtifactResponses[keyof RuntimeArtifactsUploadArtifactResponses];

export type RuntimeArtifactsReadArtifactData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Artifact Id
         */
        artifact_id: string;
    };
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtime-artifacts/{artifact_id}';
};

export type RuntimeArtifactsReadArtifactErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeArtifactsReadArtifactError = RuntimeArtifactsReadArtifactErrors[keyof RuntimeArtifactsReadArtifactErrors];

export type RuntimeArtifactsReadArtifactResponses = {
    /**
     * Successful Response
     */
    200: ArtifactPublic;
};

export type RuntimeArtifactsReadArtifactResponse = RuntimeArtifactsReadArtifactResponses[keyof RuntimeArtifactsReadArtifactResponses];

export type RuntimeArtifactsCreateReleaseData = {
    body: ReleaseCreate;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtime-artifacts/releases';
};

export type RuntimeArtifactsCreateReleaseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeArtifactsCreateReleaseError = RuntimeArtifactsCreateReleaseErrors[keyof RuntimeArtifactsCreateReleaseErrors];

export type RuntimeArtifactsCreateReleaseResponses = {
    /**
     * Successful Response
     */
    201: ReleasePublic;
};

export type RuntimeArtifactsCreateReleaseResponse = RuntimeArtifactsCreateReleaseResponses[keyof RuntimeArtifactsCreateReleaseResponses];

export type RuntimeArtifactsReadReleaseData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Release Id
         */
        release_id: string;
    };
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtime-artifacts/releases/{release_id}';
};

export type RuntimeArtifactsReadReleaseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeArtifactsReadReleaseError = RuntimeArtifactsReadReleaseErrors[keyof RuntimeArtifactsReadReleaseErrors];

export type RuntimeArtifactsReadReleaseResponses = {
    /**
     * Successful Response
     */
    200: ReleasePublic;
};

export type RuntimeArtifactsReadReleaseResponse = RuntimeArtifactsReadReleaseResponses[keyof RuntimeArtifactsReadReleaseResponses];

export type RuntimeArtifactsRetryDeploymentData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Deployment Id
         */
        deployment_id: string;
    };
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtime-artifacts/deployments/{deployment_id}/retry';
};

export type RuntimeArtifactsRetryDeploymentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeArtifactsRetryDeploymentError = RuntimeArtifactsRetryDeploymentErrors[keyof RuntimeArtifactsRetryDeploymentErrors];

export type RuntimeArtifactsRetryDeploymentResponses = {
    /**
     * Successful Response
     */
    201: DeploymentPublic;
};

export type RuntimeArtifactsRetryDeploymentResponse = RuntimeArtifactsRetryDeploymentResponses[keyof RuntimeArtifactsRetryDeploymentResponses];

export type RuntimeArtifactsRollbackDeploymentData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Deployment Id
         */
        deployment_id: string;
    };
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtime-artifacts/deployments/{deployment_id}/rollback';
};

export type RuntimeArtifactsRollbackDeploymentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeArtifactsRollbackDeploymentError = RuntimeArtifactsRollbackDeploymentErrors[keyof RuntimeArtifactsRollbackDeploymentErrors];

export type RuntimeArtifactsRollbackDeploymentResponses = {
    /**
     * Successful Response
     */
    201: ReleasePublic;
};

export type RuntimeArtifactsRollbackDeploymentResponse = RuntimeArtifactsRollbackDeploymentResponses[keyof RuntimeArtifactsRollbackDeploymentResponses];

export type NodeArtifactsDownloadArtifactData = {
    body?: never;
    path: {
        /**
         * Deployment Id
         */
        deployment_id: string;
    };
    query: {
        /**
         * Token
         */
        token: string;
    };
    url: '/api/v1/node/artifacts/{deployment_id}/download';
};

export type NodeArtifactsDownloadArtifactErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NodeArtifactsDownloadArtifactError = NodeArtifactsDownloadArtifactErrors[keyof NodeArtifactsDownloadArtifactErrors];

export type NodeArtifactsDownloadArtifactResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RuntimeNodesListTokensData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtimes/nodes/enrollment-tokens';
};

export type RuntimeNodesListTokensErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeNodesListTokensError = RuntimeNodesListTokensErrors[keyof RuntimeNodesListTokensErrors];

export type RuntimeNodesListTokensResponses = {
    /**
     * Successful Response
     */
    200: EnrollmentTokensPublic;
};

export type RuntimeNodesListTokensResponse = RuntimeNodesListTokensResponses[keyof RuntimeNodesListTokensResponses];

export type RuntimeNodesCreateTokenData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtimes/nodes/enrollment-tokens';
};

export type RuntimeNodesCreateTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeNodesCreateTokenError = RuntimeNodesCreateTokenErrors[keyof RuntimeNodesCreateTokenErrors];

export type RuntimeNodesCreateTokenResponses = {
    /**
     * Successful Response
     */
    201: EnrollmentTokenCreated;
};

export type RuntimeNodesCreateTokenResponse = RuntimeNodesCreateTokenResponses[keyof RuntimeNodesCreateTokenResponses];

export type RuntimeNodesListNodesData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtimes/nodes';
};

export type RuntimeNodesListNodesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeNodesListNodesError = RuntimeNodesListNodesErrors[keyof RuntimeNodesListNodesErrors];

export type RuntimeNodesListNodesResponses = {
    /**
     * Successful Response
     */
    200: NodesPublic;
};

export type RuntimeNodesListNodesResponse = RuntimeNodesListNodesResponses[keyof RuntimeNodesListNodesResponses];

export type RuntimeNodesReadNodeData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Node Id
         */
        node_id: string;
    };
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtimes/nodes/{node_id}';
};

export type RuntimeNodesReadNodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeNodesReadNodeError = RuntimeNodesReadNodeErrors[keyof RuntimeNodesReadNodeErrors];

export type RuntimeNodesReadNodeResponses = {
    /**
     * Successful Response
     */
    200: NodePublic;
};

export type RuntimeNodesReadNodeResponse = RuntimeNodesReadNodeResponses[keyof RuntimeNodesReadNodeResponses];

export type RuntimeNodesConfigureNodeRuntimeData = {
    body: NodeRuntimeUpsert;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Node Id
         */
        node_id: string;
    };
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtimes/nodes/{node_id}/runtime';
};

export type RuntimeNodesConfigureNodeRuntimeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeNodesConfigureNodeRuntimeError = RuntimeNodesConfigureNodeRuntimeErrors[keyof RuntimeNodesConfigureNodeRuntimeErrors];

export type RuntimeNodesConfigureNodeRuntimeResponses = {
    /**
     * Successful Response
     */
    200: NodeRuntimePublic;
};

export type RuntimeNodesConfigureNodeRuntimeResponse = RuntimeNodesConfigureNodeRuntimeResponses[keyof RuntimeNodesConfigureNodeRuntimeResponses];

export type RuntimeNodesRevokeNodeData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Node Id
         */
        node_id: string;
    };
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtimes/nodes/{node_id}/credential';
};

export type RuntimeNodesRevokeNodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeNodesRevokeNodeError = RuntimeNodesRevokeNodeErrors[keyof RuntimeNodesRevokeNodeErrors];

export type RuntimeNodesRevokeNodeResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RuntimeNodesRevokeNodeResponse = RuntimeNodesRevokeNodeResponses[keyof RuntimeNodesRevokeNodeResponses];

export type RuntimeNodesRevokeTokenData = {
    body?: never;
    headers?: {
        /**
         * X-Namespace-Id
         */
        'X-Namespace-Id'?: string | null;
    };
    path: {
        /**
         * Token Id
         */
        token_id: string;
    };
    query?: {
        /**
         * Namespace Id
         */
        namespace_id?: string | null;
    };
    url: '/api/v1/runtimes/nodes/enrollment-tokens/{token_id}';
};

export type RuntimeNodesRevokeTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RuntimeNodesRevokeTokenError = RuntimeNodesRevokeTokenErrors[keyof RuntimeNodesRevokeTokenErrors];

export type RuntimeNodesRevokeTokenResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RuntimeNodesRevokeTokenResponse = RuntimeNodesRevokeTokenResponses[keyof RuntimeNodesRevokeTokenResponses];

export type NodeEnrollmentEnrollNodeData = {
    body: NodeEnrollInput;
    path?: never;
    query?: never;
    url: '/api/v1/node/enroll';
};

export type NodeEnrollmentEnrollNodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NodeEnrollmentEnrollNodeError = NodeEnrollmentEnrollNodeErrors[keyof NodeEnrollmentEnrollNodeErrors];

export type NodeEnrollmentEnrollNodeResponses = {
    /**
     * Successful Response
     */
    201: NodeEnrollResult;
};

export type NodeEnrollmentEnrollNodeResponse = NodeEnrollmentEnrollNodeResponses[keyof NodeEnrollmentEnrollNodeResponses];

export type PrivateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PrivateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrivateCreateUserError = PrivateCreateUserErrors[keyof PrivateCreateUserErrors];

export type PrivateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PrivateCreateUserResponse = PrivateCreateUserResponses[keyof PrivateCreateUserResponses];
