from pathlib import Path
from typing import BinaryIO, Protocol


class ArtifactStorage(Protocol):
    def put_once(self, key: str, source: Path) -> None: ...
    def open(self, key: str) -> BinaryIO: ...
    def issue_download(self, key: str, expires_in_seconds: int) -> str: ...
