from pathlib import Path
from typing import Protocol


class ReadableBinaryStream(Protocol):
    def read(self, size: int = -1) -> bytes: ...
    def close(self) -> None: ...


class ArtifactStorage(Protocol):
    def put_once(self, key: str, source: Path) -> None: ...
    def open(self, key: str) -> ReadableBinaryStream: ...
    def issue_download(self, key: str, expires_in_seconds: int) -> str: ...
