"""add v0.5 managed capabilities releases and approvals

Revision ID: 3c1717dcaceb
Revises: c4f6a8d2e913
Create Date: 2026-07-13 10:49:19.985654

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = "3c1717dcaceb"
down_revision = "c4f6a8d2e913"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE agenttaskstatus ADD VALUE IF NOT EXISTS 'awaiting_approval'")
    op.execute("ALTER TYPE agenteventtype ADD VALUE IF NOT EXISTS 'approval_requested'")
    op.execute("ALTER TYPE agenteventtype ADD VALUE IF NOT EXISTS 'approval_resolved'")
    op.execute("ALTER TYPE agenteventtype ADD VALUE IF NOT EXISTS 'approval_expired'")
    op.create_table(
        "cli_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "token_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "client_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"], ["cli_session.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cli_session_expires_at"), "cli_session", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_cli_session_family_id"), "cli_session", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_cli_session_token_hash"), "cli_session", ["token_hash"], unique=True
    )
    op.create_index(
        op.f("ix_cli_session_user_id"), "cli_session", ["user_id"], unique=False
    )
    op.create_table(
        "tool_definition",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "harness_type", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "tool_key", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column(
            "display_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "source", sa.Enum("builtin", "mcp", name="toolsource"), nullable=False
        ),
        sa.Column(
            "risk_level", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "baseline_policy",
            sa.Enum("allow", "require_approval", "forbidden", name="toolbaseline"),
            nullable=False,
        ),
        sa.Column("supports_approval", sa.Boolean(), nullable=False),
        sa.Column(
            "adapter_schema_version",
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=False,
        ),
        sa.Column(
            "schema_digest", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "harness_type",
            "tool_key",
            "adapter_schema_version",
            name="uq_tool_definition",
        ),
    )
    op.create_index(
        op.f("ix_tool_definition_tool_key"),
        "tool_definition",
        ["tool_key"],
        unique=False,
    )
    op.create_table(
        "mcp_server",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("namespace_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["namespace_id"], ["namespace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace_id", "slug", name="uq_mcp_namespace_slug"),
    )
    op.create_index(
        op.f("ix_mcp_server_namespace_id"), "mcp_server", ["namespace_id"], unique=False
    )
    op.create_table(
        "namespace_tool_policy",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("namespace_id", sa.Uuid(), nullable=False),
        sa.Column("tool_definition_id", sa.Uuid(), nullable=False),
        sa.Column(
            "policy",
            sa.Enum(
                "inherit",
                "allow",
                "deny",
                "disabled",
                "require_approval",
                name="toolpolicy",
            ),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["namespace_id"], ["namespace.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tool_definition_id"], ["tool_definition.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "namespace_id", "tool_definition_id", name="uq_namespace_tool_policy"
        ),
    )
    op.create_index(
        op.f("ix_namespace_tool_policy_namespace_id"),
        "namespace_tool_policy",
        ["namespace_id"],
        unique=False,
    )
    op.create_table(
        "neomua_plugin",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("namespace_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["namespace_id"], ["namespace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace_id", "slug", name="uq_plugin_namespace_slug"),
    )
    op.create_index(
        op.f("ix_neomua_plugin_namespace_id"),
        "neomua_plugin",
        ["namespace_id"],
        unique=False,
    )
    op.create_table(
        "skill_definition",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("namespace_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["namespace_id"], ["namespace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace_id", "slug", name="uq_skill_namespace_slug"),
    )
    op.create_index(
        op.f("ix_skill_definition_namespace_id"),
        "skill_definition",
        ["namespace_id"],
        unique=False,
    )
    op.create_table(
        "agent_release",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("namespace_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column(
            "version", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("draft_revision", sa.Integer(), nullable=False),
        sa.Column(
            "resolved_spec_schema_version",
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=False,
        ),
        sa.Column("resolved_spec", sa.JSON(), nullable=False),
        sa.Column(
            "resolved_spec_digest",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("dependency_lock", sa.JSON(), nullable=False),
        sa.Column(
            "manifest_digest",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("signature", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "signing_public_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "idempotency_key",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agent_definition.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["namespace_id"], ["namespace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "version", name="uq_agent_release_version"),
        sa.UniqueConstraint(
            "namespace_id", "idempotency_key", name="uq_agent_release_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_agent_release_agent_id"), "agent_release", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_release_namespace_id"),
        "agent_release",
        ["namespace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_release_resolved_spec_digest"),
        "agent_release",
        ["resolved_spec_digest"],
        unique=False,
    )
    op.create_table(
        "mcp_server_revision",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("server_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "transport",
            sa.Enum("stdio", "streamable_http", "sse", name="mcptransport"),
            nullable=False,
        ),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column(
            "config_sha256", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "protocol_version",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("deprecated", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["server_id"], ["mcp_server.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("server_id", "revision", name="uq_mcp_revision"),
    )
    op.create_index(
        op.f("ix_mcp_server_revision_server_id"),
        "mcp_server_revision",
        ["server_id"],
        unique=False,
    )
    op.create_table(
        "plugin_draft",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plugin_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "harness_type", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "adapter_schema_version",
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=False,
        ),
        sa.Column("adapter_config", sa.JSON(), nullable=False),
        sa.Column("components", sa.JSON(), nullable=False),
        sa.Column("validation_result", sa.JSON(), nullable=True),
        sa.Column("validated_revision", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["plugin_id"], ["neomua_plugin.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plugin_id"),
    )
    op.create_table(
        "plugin_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plugin_id", sa.Uuid(), nullable=False),
        sa.Column(
            "version", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "harness_type", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "adapter_schema_version",
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=False,
        ),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("dependency_lock", sa.JSON(), nullable=False),
        sa.Column(
            "manifest_digest",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("signature", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "signing_public_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("deprecated", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["plugin_id"], ["neomua_plugin.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plugin_id", "version", name="uq_plugin_version"),
    )
    op.create_index(
        op.f("ix_plugin_version_plugin_id"),
        "plugin_version",
        ["plugin_id"],
        unique=False,
    )
    op.create_table(
        "skill_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column(
            "version", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "content_sha256",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column(
            "storage_key", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False
        ),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column(
            "invocation_mode",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("platforms", sa.JSON(), nullable=False),
        sa.Column("required_capabilities", sa.JSON(), nullable=False),
        sa.Column("content_types", sa.JSON(), nullable=False),
        sa.Column("validation_result", sa.JSON(), nullable=False),
        sa.Column("deprecated", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["skill_definition.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("skill_id", "version", name="uq_skill_version"),
    )
    op.create_index(
        op.f("ix_skill_version_content_sha256"),
        "skill_version",
        ["content_sha256"],
        unique=False,
    )
    op.create_index(
        op.f("ix_skill_version_skill_id"), "skill_version", ["skill_id"], unique=False
    )
    op.create_table(
        "agent_activation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("namespace_id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column(
            "idempotency_key",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "validating",
                "deploying",
                "active",
                "partial",
                "failed",
                "rolled_back",
                "expired",
                name="activationstatus",
            ),
            nullable=False,
        ),
        sa.Column("rollback_of_activation_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["namespace_id"], ["namespace.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["release_id"], ["agent_release.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["rollback_of_activation_id"], ["agent_activation.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "namespace_id", "idempotency_key", name="uq_agent_activation_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_agent_activation_namespace_id"),
        "agent_activation",
        ["namespace_id"],
        unique=False,
    )
    op.create_table(
        "agent_draft_mcp",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_draft_id", sa.Uuid(), nullable=False),
        sa.Column("server_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("allowed_tools", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_draft_id"], ["agent_draft.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"], ["mcp_server_revision.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["server_id"], ["mcp_server.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_draft_id", "server_id", name="uq_agent_draft_mcp"),
    )
    op.create_index(
        op.f("ix_agent_draft_mcp_agent_draft_id"),
        "agent_draft_mcp",
        ["agent_draft_id"],
        unique=False,
    )
    op.create_table(
        "agent_draft_plugin",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_draft_id", sa.Uuid(), nullable=False),
        sa.Column("plugin_id", sa.Uuid(), nullable=False),
        sa.Column("plugin_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_draft_id"], ["agent_draft.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["plugin_id"], ["neomua_plugin.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["plugin_version_id"], ["plugin_version.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agent_draft_id", "plugin_id", name="uq_agent_draft_plugin"
        ),
    )
    op.create_index(
        op.f("ix_agent_draft_plugin_agent_draft_id"),
        "agent_draft_plugin",
        ["agent_draft_id"],
        unique=False,
    )
    op.create_table(
        "agent_draft_skill",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_draft_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("skill_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_draft_id"], ["agent_draft.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["skill_definition.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["skill_version_id"], ["skill_version.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_draft_id", "skill_id", name="uq_agent_draft_skill"),
    )
    op.create_index(
        op.f("ix_agent_draft_skill_agent_draft_id"),
        "agent_draft_skill",
        ["agent_draft_id"],
        unique=False,
    )
    op.create_table(
        "agent_draft_tool_policy",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_draft_id", sa.Uuid(), nullable=False),
        sa.Column(
            "tool_key", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column(
            "policy",
            sa.Enum(
                "inherit",
                "allow",
                "deny",
                "disabled",
                "require_approval",
                name="agenttoolpolicy",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_draft_id"], ["agent_draft.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_draft_id", "tool_key", name="uq_agent_draft_tool"),
    )
    op.create_index(
        op.f("ix_agent_draft_tool_policy_agent_draft_id"),
        "agent_draft_tool_policy",
        ["agent_draft_id"],
        unique=False,
    )
    op.create_table(
        "agent_release_component",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column(
            "component_type",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column(
            "component_key",
            sqlmodel.sql.sqltypes.AutoString(length=512),
            nullable=False,
        ),
        sa.Column(
            "component_version",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=True,
        ),
        sa.Column("source_chain", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"], ["agent_release.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_release_component_release_id"),
        "agent_release_component",
        ["release_id"],
        unique=False,
    )
    op.create_table(
        "mcp_target_binding",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("runtime_profile_id", sa.Uuid(), nullable=False),
        sa.Column(
            "secret_ref", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "capability_fingerprint",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "secret_fingerprint",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "tool_digest", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum(
                "unverified",
                "pending",
                "verified",
                "stale",
                "failed",
                "unsupported",
                "expired",
                name="mcptargetstatus",
            ),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["revision_id"], ["mcp_server_revision.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["runtime_profile_id"], ["runtime_profile.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("revision_id", "runtime_profile_id", name="uq_mcp_target"),
    )
    op.create_index(
        op.f("ix_mcp_target_binding_revision_id"),
        "mcp_target_binding",
        ["revision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_target_binding_runtime_profile_id"),
        "mcp_target_binding",
        ["runtime_profile_id"],
        unique=False,
    )
    op.create_table(
        "mcp_runtime_instance",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("target_binding_id", sa.Uuid(), nullable=False),
        sa.Column(
            "instance_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "starting",
                "ready",
                "reconnecting",
                "stale",
                "failed",
                "stopping",
                "stopped",
                name="mcpruntimestatus",
            ),
            nullable=False,
        ),
        sa.Column("reference_count", sa.Integer(), nullable=False),
        sa.Column("restart_count", sa.Integer(), nullable=False),
        sa.Column("restart_budget", sa.Integer(), nullable=False),
        sa.Column(
            "tool_digest", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("last_error", sa.JSON(), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_binding_id"], ["mcp_target_binding.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instance_key", name="uq_mcp_runtime_instance_key"),
    )
    op.create_index(
        op.f("ix_mcp_runtime_instance_instance_key"),
        "mcp_runtime_instance",
        ["instance_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_runtime_instance_target_binding_id"),
        "mcp_runtime_instance",
        ["target_binding_id"],
        unique=False,
    )
    op.create_table(
        "mcp_runtime_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column(
            "event_type", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["instance_id"], ["mcp_runtime_instance.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mcp_runtime_event_instance_id"),
        "mcp_runtime_event",
        ["instance_id"],
        unique=False,
    )
    op.create_table(
        "runtime_agent_release",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("namespace_id", sa.Uuid(), nullable=False),
        sa.Column("runtime_profile_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("current_release_id", sa.Uuid(), nullable=False),
        sa.Column("previous_release_id", sa.Uuid(), nullable=True),
        sa.Column(
            "applied_digest",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column(
            "materialization_digest",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agent_definition.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["current_release_id"], ["agent_release.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["namespace_id"], ["namespace.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["previous_release_id"], ["agent_release.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["runtime_profile_id"], ["runtime_profile.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "runtime_profile_id", "agent_id", name="uq_runtime_agent_release"
        ),
    )
    op.create_index(
        op.f("ix_runtime_agent_release_agent_id"),
        "runtime_agent_release",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_runtime_agent_release_namespace_id"),
        "runtime_agent_release",
        ["namespace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_runtime_agent_release_runtime_profile_id"),
        "runtime_agent_release",
        ["runtime_profile_id"],
        unique=False,
    )
    op.create_table(
        "agent_deployment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("activation_id", sa.Uuid(), nullable=False),
        sa.Column("runtime_profile_id", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "prechecking",
                "incompatible",
                "pending",
                "dispatched",
                "applying",
                "applied",
                "failed",
                "expired",
                "rolled_back",
                name="agentdeploymentstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "capability_fingerprint",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "applied_digest", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["activation_id"], ["agent_activation.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["runtime_profile_id"], ["runtime_profile.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "activation_id",
            "runtime_profile_id",
            "attempt",
            name="uq_agent_deployment_attempt",
        ),
    )
    op.create_index(
        op.f("ix_agent_deployment_activation_id"),
        "agent_deployment",
        ["activation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_deployment_runtime_profile_id"),
        "agent_deployment",
        ["runtime_profile_id"],
        unique=False,
    )
    op.create_table(
        "mcp_platform_secret",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("target_binding_id", sa.Uuid(), nullable=False),
        sa.Column(
            "secret_ciphertext", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "secret_masked",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_binding_id"], ["mcp_target_binding.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_binding_id"),
    )
    op.create_table(
        "mcp_validation_attempt",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("target_binding_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "unverified",
                "pending",
                "verified",
                "stale",
                "failed",
                "unsupported",
                "expired",
                name="mcpvalidationstatus",
            ),
            nullable=False,
        ),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["target_binding_id"], ["mcp_target_binding.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mcp_validation_attempt_target_binding_id"),
        "mcp_validation_attempt",
        ["target_binding_id"],
        unique=False,
    )
    op.create_table(
        "mcp_tool_snapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("validation_attempt_id", sa.Uuid(), nullable=False),
        sa.Column(
            "qualified_name",
            sqlmodel.sql.sqltypes.AutoString(length=512),
            nullable=False,
        ),
        sa.Column(
            "original_name",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("input_schema", sa.JSON(), nullable=False),
        sa.Column(
            "schema_digest", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["validation_attempt_id"], ["mcp_validation_attempt.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "validation_attempt_id", "qualified_name", name="uq_mcp_snapshot_tool"
        ),
    )
    op.create_index(
        op.f("ix_mcp_tool_snapshot_validation_attempt_id"),
        "mcp_tool_snapshot",
        ["validation_attempt_id"],
        unique=False,
    )
    op.create_table(
        "tool_approval_request",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("namespace_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("task_revision", sa.Integer(), nullable=False),
        sa.Column(
            "tool_call_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "tool_qualified_name",
            sqlmodel.sql.sqltypes.AutoString(length=512),
            nullable=False,
        ),
        sa.Column("redacted_args", sa.JSON(), nullable=False),
        sa.Column(
            "args_digest", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "denied",
                "expired",
                "cancelled",
                name="approvalstatus",
            ),
            nullable=False,
        ),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column(
            "decision_reason",
            sqlmodel.sql.sqltypes.AutoString(length=1024),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["namespace_id"], ["namespace.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resolved_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["task_id"], ["agent_task.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "task_id",
            "task_revision",
            "tool_call_id",
            "args_digest",
            name="uq_tool_approval_call",
        ),
    )
    op.create_index(
        op.f("ix_tool_approval_request_namespace_id"),
        "tool_approval_request",
        ["namespace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tool_approval_request_task_id"),
        "tool_approval_request",
        ["task_id"],
        unique=False,
    )
    op.add_column(
        "agent_session", sa.Column("agent_release_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "agent_session", sa.Column("runtime_agent_release_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "agent_session",
        sa.Column(
            "resolved_spec_digest",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "fk_agent_session_runtime_agent_release",
        "agent_session",
        "runtime_agent_release",
        ["runtime_agent_release_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_agent_session_agent_release",
        "agent_session",
        "agent_release",
        ["agent_release_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("agent_task", sa.Column("agent_release_id", sa.Uuid(), nullable=True))
    op.add_column(
        "agent_task", sa.Column("runtime_agent_release_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "agent_task",
        sa.Column(
            "resolved_spec_digest",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "fk_agent_task_runtime_agent_release",
        "agent_task",
        "runtime_agent_release",
        ["runtime_agent_release_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_agent_task_agent_release",
        "agent_task",
        "agent_release",
        ["agent_release_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_agent_task_agent_release", "agent_task", type_="foreignkey")
    op.drop_constraint(
        "fk_agent_task_runtime_agent_release", "agent_task", type_="foreignkey"
    )
    op.drop_column("agent_task", "resolved_spec_digest")
    op.drop_column("agent_task", "runtime_agent_release_id")
    op.drop_column("agent_task", "agent_release_id")
    op.drop_constraint(
        "fk_agent_session_agent_release", "agent_session", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_agent_session_runtime_agent_release", "agent_session", type_="foreignkey"
    )
    op.drop_column("agent_session", "resolved_spec_digest")
    op.drop_column("agent_session", "runtime_agent_release_id")
    op.drop_column("agent_session", "agent_release_id")
    op.drop_index(
        op.f("ix_tool_approval_request_task_id"), table_name="tool_approval_request"
    )
    op.drop_index(
        op.f("ix_tool_approval_request_namespace_id"),
        table_name="tool_approval_request",
    )
    op.drop_table("tool_approval_request")
    op.drop_index(
        op.f("ix_mcp_tool_snapshot_validation_attempt_id"),
        table_name="mcp_tool_snapshot",
    )
    op.drop_table("mcp_tool_snapshot")
    op.drop_index(
        op.f("ix_mcp_validation_attempt_target_binding_id"),
        table_name="mcp_validation_attempt",
    )
    op.drop_table("mcp_validation_attempt")
    op.drop_table("mcp_platform_secret")
    op.drop_index(
        op.f("ix_agent_deployment_runtime_profile_id"), table_name="agent_deployment"
    )
    op.drop_index(
        op.f("ix_agent_deployment_activation_id"), table_name="agent_deployment"
    )
    op.drop_table("agent_deployment")
    op.drop_index(
        op.f("ix_runtime_agent_release_runtime_profile_id"),
        table_name="runtime_agent_release",
    )
    op.drop_index(
        op.f("ix_runtime_agent_release_namespace_id"),
        table_name="runtime_agent_release",
    )
    op.drop_index(
        op.f("ix_runtime_agent_release_agent_id"), table_name="runtime_agent_release"
    )
    op.drop_table("runtime_agent_release")
    op.drop_index(
        op.f("ix_mcp_target_binding_runtime_profile_id"),
        table_name="mcp_target_binding",
    )
    op.drop_index(
        op.f("ix_mcp_target_binding_revision_id"), table_name="mcp_target_binding"
    )
    op.drop_index(
        op.f("ix_mcp_runtime_event_instance_id"), table_name="mcp_runtime_event"
    )
    op.drop_table("mcp_runtime_event")
    op.drop_index(
        op.f("ix_mcp_runtime_instance_target_binding_id"),
        table_name="mcp_runtime_instance",
    )
    op.drop_index(
        op.f("ix_mcp_runtime_instance_instance_key"), table_name="mcp_runtime_instance"
    )
    op.drop_table("mcp_runtime_instance")
    op.drop_table("mcp_target_binding")
    op.drop_index(
        op.f("ix_agent_release_component_release_id"),
        table_name="agent_release_component",
    )
    op.drop_table("agent_release_component")
    op.drop_index(
        op.f("ix_agent_draft_tool_policy_agent_draft_id"),
        table_name="agent_draft_tool_policy",
    )
    op.drop_table("agent_draft_tool_policy")
    op.drop_index(
        op.f("ix_agent_draft_skill_agent_draft_id"), table_name="agent_draft_skill"
    )
    op.drop_table("agent_draft_skill")
    op.drop_index(
        op.f("ix_agent_draft_plugin_agent_draft_id"), table_name="agent_draft_plugin"
    )
    op.drop_table("agent_draft_plugin")
    op.drop_index(
        op.f("ix_agent_draft_mcp_agent_draft_id"), table_name="agent_draft_mcp"
    )
    op.drop_table("agent_draft_mcp")
    op.drop_index(
        op.f("ix_agent_activation_namespace_id"), table_name="agent_activation"
    )
    op.drop_table("agent_activation")
    op.drop_index(op.f("ix_skill_version_skill_id"), table_name="skill_version")
    op.drop_index(op.f("ix_skill_version_content_sha256"), table_name="skill_version")
    op.drop_table("skill_version")
    op.drop_index(op.f("ix_plugin_version_plugin_id"), table_name="plugin_version")
    op.drop_table("plugin_version")
    op.drop_table("plugin_draft")
    op.drop_index(
        op.f("ix_mcp_server_revision_server_id"), table_name="mcp_server_revision"
    )
    op.drop_table("mcp_server_revision")
    op.drop_index(
        op.f("ix_agent_release_resolved_spec_digest"), table_name="agent_release"
    )
    op.drop_index(op.f("ix_agent_release_namespace_id"), table_name="agent_release")
    op.drop_index(op.f("ix_agent_release_agent_id"), table_name="agent_release")
    op.drop_table("agent_release")
    op.drop_index(
        op.f("ix_skill_definition_namespace_id"), table_name="skill_definition"
    )
    op.drop_table("skill_definition")
    op.drop_index(op.f("ix_neomua_plugin_namespace_id"), table_name="neomua_plugin")
    op.drop_table("neomua_plugin")
    op.drop_index(
        op.f("ix_namespace_tool_policy_namespace_id"),
        table_name="namespace_tool_policy",
    )
    op.drop_table("namespace_tool_policy")
    op.drop_index(op.f("ix_mcp_server_namespace_id"), table_name="mcp_server")
    op.drop_table("mcp_server")
    op.drop_index(op.f("ix_tool_definition_tool_key"), table_name="tool_definition")
    op.drop_table("tool_definition")
    op.drop_index(op.f("ix_cli_session_user_id"), table_name="cli_session")
    op.drop_index(op.f("ix_cli_session_token_hash"), table_name="cli_session")
    op.drop_index(op.f("ix_cli_session_family_id"), table_name="cli_session")
    op.drop_index(op.f("ix_cli_session_expires_at"), table_name="cli_session")
    op.drop_table("cli_session")
    for enum_name in (
        "approvalstatus",
        "agentdeploymentstatus",
        "activationstatus",
        "mcpvalidationstatus",
        "mcpruntimestatus",
        "mcptargetstatus",
        "mcptransport",
        "agenttoolpolicy",
        "toolpolicy",
        "toolbaseline",
        "toolsource",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
