"""add v0.6 project conversation workflow workspace

Revision ID: b5876b129fbd
Revises: 3c1717dcaceb
Create Date: 2026-07-13 14:50:47.952858

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5876b129fbd'
down_revision = '3c1717dcaceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spec_standard',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope_type', sa.Enum('platform', 'namespace', name='specscopetype'), nullable=False),
    sa.Column('namespace_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_type', 'namespace_id', 'slug', name='uq_spec_standard_scope_slug')
    )
    op.create_index(op.f('ix_spec_standard_namespace_id'), 'spec_standard', ['namespace_id'], unique=False)
    op.create_index(
        'uq_spec_standard_platform_slug',
        'spec_standard',
        ['slug'],
        unique=True,
        postgresql_where=sa.text("scope_type = 'platform' AND namespace_id IS NULL"),
    )
    op.create_table('workflow_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope_type', sa.Enum('platform', 'namespace', name='workflowscopetype'), nullable=False),
    sa.Column('namespace_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='workflowtemplatestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_type', 'namespace_id', 'slug', name='uq_workflow_template_scope_slug')
    )
    op.create_index(op.f('ix_workflow_template_namespace_id'), 'workflow_template', ['namespace_id'], unique=False)
    op.create_index(
        'uq_workflow_template_platform_slug',
        'workflow_template',
        ['slug'],
        unique=True,
        postgresql_where=sa.text("scope_type = 'platform' AND namespace_id IS NULL"),
    )
    op.create_table('spec_standard_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('standard_id', sa.Uuid(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('manifest', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('content_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('storage_ref', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('status', sa.Enum('active', 'deprecated', name='specversionstatus'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['standard_id'], ['spec_standard.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('standard_id', 'content_digest', name='uq_spec_standard_digest'),
    sa.UniqueConstraint('standard_id', 'version', name='uq_spec_standard_version')
    )
    op.create_index(op.f('ix_spec_standard_version_standard_id'), 'spec_standard_version', ['standard_id'], unique=False)
    op.create_table('workflow_application',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('component_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('route_slug', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('build_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('shell_version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_slug', name='uq_workflow_application_route'),
    sa.UniqueConstraint('template_id', name='uq_workflow_application_template')
    )
    op.create_table('workflow_template_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('manifest', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('package_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('sdk_version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'deprecated', 'blocked', name='workflowversionstatus'), nullable=False),
    sa.Column('build_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_template.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'package_digest', name='uq_workflow_template_digest'),
    sa.UniqueConstraint('template_id', 'version', name='uq_workflow_template_version')
    )
    op.create_index(op.f('ix_workflow_template_version_template_id'), 'workflow_template_version', ['template_id'], unique=False)
    op.create_table('namespace_workflow_enablement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('namespace_id', sa.Uuid(), nullable=False),
    sa.Column('template_version_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespace.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_version_id'], ['workflow_template_version.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace_id', 'template_version_id', name='uq_namespace_workflow_version')
    )
    op.create_index(op.f('ix_namespace_workflow_enablement_namespace_id'), 'namespace_workflow_enablement', ['namespace_id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('namespace_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='projectstatus'), nullable=False),
    sa.Column('default_runtime_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_runtime_id'], ['runtime_profile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace_id', 'slug', name='uq_project_namespace_slug')
    )
    op.create_index(op.f('ix_project_namespace_id'), 'project', ['namespace_id'], unique=False)
    op.create_table('workflow_edge_definition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_node_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('target_node_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('condition_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('condition_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['template_version_id'], ['workflow_template_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_version_id', 'source_node_key', 'target_node_key', 'condition_key', name='uq_workflow_edge')
    )
    op.create_index(op.f('ix_workflow_edge_definition_template_version_id'), 'workflow_edge_definition', ['template_version_id'], unique=False)
    op.create_table('workflow_node_definition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_version_id', sa.Uuid(), nullable=False),
    sa.Column('node_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('node_type', sa.Enum('human', 'agent', 'code', name='workflownodetype'), nullable=False),
    sa.Column('confirmation_mode', sa.Enum('process_confirmation', 'result_confirmation', 'no_confirmation', name='confirmationmode'), nullable=False),
    sa.Column('input_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('output_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('runtime_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('agent_release_id', sa.Uuid(), nullable=True),
    sa.Column('handler_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('entry_validator_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('exit_validator_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('skippable', sa.Boolean(), nullable=False),
    sa.Column('skip_output', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('side_effecting', sa.Boolean(), nullable=False),
    sa.Column('join_policy', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_release_id'], ['agent_release.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_version_id'], ['workflow_template_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_version_id', 'node_key', name='uq_workflow_node_key')
    )
    op.create_index(op.f('ix_workflow_node_definition_template_version_id'), 'workflow_node_definition', ['template_version_id'], unique=False)
    op.create_table('conversation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('namespace_id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('source_conversation_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('mode', sa.Enum('chat', 'agent', name='conversationmode'), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'project', name='conversationvisibility'), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='conversationstatus'), nullable=False),
    sa.Column('runtime_id', sa.Uuid(), nullable=False),
    sa.Column('provider_config_id', sa.Uuid(), nullable=True),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('creation_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('current_context_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespace.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_config_id'], ['llm_provider_config.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['runtime_id'], ['runtime_profile.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversation.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace_id', 'creator_id', 'idempotency_key', name='uq_conversation_create_idempotency')
    )
    op.create_index(op.f('ix_conversation_creator_id'), 'conversation', ['creator_id'], unique=False)
    op.create_index(op.f('ix_conversation_namespace_id'), 'conversation', ['namespace_id'], unique=False)
    op.create_index(op.f('ix_conversation_project_id'), 'conversation', ['project_id'], unique=False)
    op.create_table('project_member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member')
    )
    op.create_index(op.f('ix_project_member_project_id'), 'project_member', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_member_user_id'), 'project_member', ['user_id'], unique=False)
    op.create_table('project_repository',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('remote_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('default_branch', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('credential_ref', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('runtime_workspace_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('unvalidated', 'available', 'unavailable', name='repositorystatus'), nullable=False),
    sa.Column('validation_error', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('validated_commit', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'remote_url', name='uq_project_repository_url')
    )
    op.create_index(op.f('ix_project_repository_project_id'), 'project_repository', ['project_id'], unique=False)
    op.create_table('workflow_instance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('namespace_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('template_version_id', sa.Uuid(), nullable=False),
    sa.Column('package_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'waiting', 'blocked', 'completed', 'failed', 'cancelled', name='workflowinstancestatus'), nullable=False),
    sa.Column('input', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('default_runtime_id', sa.Uuid(), nullable=True),
    sa.Column('runtime_resolution', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('project_context_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_runtime_id'], ['runtime_profile.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespace.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_version_id'], ['workflow_template_version.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace_id', 'idempotency_key', name='uq_workflow_instance_idempotency')
    )
    op.create_index(op.f('ix_workflow_instance_namespace_id'), 'workflow_instance', ['namespace_id'], unique=False)
    op.create_index(op.f('ix_workflow_instance_project_id'), 'workflow_instance', ['project_id'], unique=False)
    op.create_table('conversation_agent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('main', 'collaborator', name='conversationagentrole'), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('agent_release_id', sa.Uuid(), nullable=False),
    sa.Column('runtime_agent_release_id', sa.Uuid(), nullable=False),
    sa.Column('agent_session_id', sa.Uuid(), nullable=False),
    sa.Column('resolved_spec_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_definition.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['agent_release_id'], ['agent_release.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_session.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runtime_agent_release_id'], ['runtime_agent_release.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'agent_id', name='uq_conversation_agent')
    )
    op.create_index(op.f('ix_conversation_agent_conversation_id'), 'conversation_agent', ['conversation_id'], unique=False)
    op.create_index(
        'uq_conversation_main_agent',
        'conversation_agent',
        ['conversation_id'],
        unique=True,
        postgresql_where=sa.text("role = 'main'"),
    )
    op.create_table('conversation_context_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('repository_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('spec_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('content_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('content_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'revision', name='uq_conversation_snapshot_revision')
    )
    op.create_index(op.f('ix_conversation_context_snapshot_conversation_id'), 'conversation_context_snapshot', ['conversation_id'], unique=False)
    op.create_table('project_spec_location',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('location_type', sa.Enum('directory', 'file', name='speclocationtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending_initialization', 'valid', 'unavailable', name='speclocationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['project_repository.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'path', name='uq_project_spec_location_path')
    )
    op.create_index(op.f('ix_project_spec_location_project_id'), 'project_spec_location', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_spec_location_repository_id'), 'project_spec_location', ['repository_id'], unique=False)
    op.create_table('workflow_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_instance_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_instance_id', 'sequence', name='uq_workflow_event_sequence')
    )
    op.create_index(op.f('ix_workflow_event_workflow_instance_id'), 'workflow_event', ['workflow_instance_id'], unique=False)
    op.create_table('workflow_node_instance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_instance_id', sa.Uuid(), nullable=False),
    sa.Column('node_definition_id', sa.Uuid(), nullable=False),
    sa.Column('node_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('status', sa.Enum('inactive', 'ready', 'running', 'waiting_confirmation', 'completed', 'update_required', 'blocked', 'failed', 'skipped', 'needs_manual_resolution', name='workflownodestatus'), nullable=False),
    sa.Column('expected_revision', sa.Integer(), nullable=False),
    sa.Column('current_revision_id', sa.Uuid(), nullable=True),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('latest_input_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('resolved_runtime_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_definition_id'], ['workflow_node_definition.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_runtime_id'], ['runtime_profile.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_instance_id', 'node_key', name='uq_workflow_instance_node')
    )
    op.create_index(op.f('ix_workflow_node_instance_workflow_instance_id'), 'workflow_node_instance', ['workflow_instance_id'], unique=False)
    op.create_table('conversation_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('author_type', sa.Enum('user', 'model', 'agent', 'system', name='messageauthortype'), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('target_type', sa.Enum('main', 'agent', 'all', 'model', 'system', name='messagetargettype'), nullable=False),
    sa.Column('target_agent_id', sa.Uuid(), nullable=True),
    sa.Column('context_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='conversationmessagestatus'), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('reply_to_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('error', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['context_snapshot_id'], ['conversation_context_snapshot.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['conversation_message.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_task.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'idempotency_key', name='uq_conversation_message_idempotency'),
    sa.UniqueConstraint('conversation_id', 'sequence', name='uq_conversation_message_sequence')
    )
    op.create_index(op.f('ix_conversation_message_conversation_id'), 'conversation_message', ['conversation_id'], unique=False)
    op.create_index('ix_conversation_message_status', 'conversation_message', ['conversation_id', 'status'], unique=False)
    op.create_table('project_spec_binding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('spec_location_id', sa.Uuid(), nullable=False),
    sa.Column('standard_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'valid', 'conflict', name='specbindingstatus'), nullable=False),
    sa.Column('validated_commit', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('diff_preview', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spec_location_id'], ['project_spec_location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_version_id'], ['spec_standard_version.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spec_location_id', name='uq_project_spec_binding_location')
    )
    op.create_index(op.f('ix_project_spec_binding_project_id'), 'project_spec_binding', ['project_id'], unique=False)
    op.create_table('workflow_confirmation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_instance_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('mode', postgresql.ENUM('process_confirmation', 'result_confirmation', 'no_confirmation', name='confirmationmode', create_type=False), nullable=False),
    sa.Column('decision', sa.Enum('submit', 'accept', 'reject', 'skip', name='confirmationdecision'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_instance_id'], ['workflow_node_instance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_confirmation_node_instance_id'), 'workflow_confirmation', ['node_instance_id'], unique=False)
    op.create_table('workflow_gate_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_instance_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('gate_type', sa.Enum('entry', 'exit', name='workflowgatetype'), nullable=False),
    sa.Column('validator_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('validator_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('input_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_instance_id'], ['workflow_node_instance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_gate_result_node_instance_id'), 'workflow_gate_result', ['node_instance_id'], unique=False)
    op.create_table('workflow_node_execution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_instance_id', sa.Uuid(), nullable=False),
    sa.Column('input_revision', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('runtime_id', sa.Uuid(), nullable=False),
    sa.Column('agent_task_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'superseded', 'needs_manual_resolution', name='workflowexecutionstatus'), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('external_state_proof', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_task_id'], ['agent_task.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_instance_id'], ['workflow_node_instance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runtime_id'], ['runtime_profile.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_instance_id', 'attempt', name='uq_workflow_node_attempt'),
    sa.UniqueConstraint('node_instance_id', 'idempotency_key', name='uq_workflow_execution_key')
    )
    op.create_index(op.f('ix_workflow_node_execution_node_instance_id'), 'workflow_node_execution', ['node_instance_id'], unique=False)
    op.create_index('ix_workflow_node_execution_status', 'workflow_node_execution', ['node_instance_id', 'status'], unique=False)
    op.create_index(
        'uq_workflow_node_active_execution',
        'workflow_node_execution',
        ['node_instance_id', 'input_revision'],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_table('workflow_node_revision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_instance_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('input_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('output', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('output_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_instance_id'], ['workflow_node_instance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_instance_id', 'revision', name='uq_workflow_node_revision')
    )
    op.create_index(op.f('ix_workflow_node_revision_node_instance_id'), 'workflow_node_revision', ['node_instance_id'], unique=False)
    op.create_table('agent_delegation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('source_message_id', sa.Uuid(), nullable=False),
    sa.Column('source_agent_id', sa.Uuid(), nullable=False),
    sa.Column('target_agent_id', sa.Uuid(), nullable=False),
    sa.Column('input_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='delegationstatus'), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('error', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_agent_id'], ['conversation_agent.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_message_id'], ['conversation_message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_agent_id'], ['conversation_agent.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_task.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'idempotency_key', name='uq_agent_delegation_idempotency')
    )
    op.create_index(op.f('ix_agent_delegation_conversation_id'), 'agent_delegation', ['conversation_id'], unique=False)
    op.create_table('conversation_attachment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('storage_ref', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('scan_status', sa.Enum('pending', 'clean', 'rejected', name='attachmentscanstatus'), nullable=False),
    sa.Column('scan_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['conversation_message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'content_digest', name='uq_conversation_attachment_content')
    )
    op.create_index(op.f('ix_conversation_attachment_conversation_id'), 'conversation_attachment', ['conversation_id'], unique=False)
    op.create_table('workflow_artifact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_revision_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('storage_type', sa.Enum('git', 'object', 'inline', name='artifactstoragetype'), nullable=False),
    sa.Column('storage_ref', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('content_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_revision_id'], ['workflow_node_revision.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_artifact_node_revision_id'), 'workflow_artifact', ['node_revision_id'], unique=False)
    op.create_foreign_key(
        'fk_conversation_current_context_snapshot',
        'conversation',
        'conversation_context_snapshot',
        ['current_context_snapshot_id'],
        ['id'],
        ondelete='RESTRICT',
    )
    op.create_foreign_key(
        'fk_workflow_node_current_revision',
        'workflow_node_instance',
        'workflow_node_revision',
        ['current_revision_id'],
        ['id'],
        ondelete='RESTRICT',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_workflow_node_current_revision', 'workflow_node_instance', type_='foreignkey')
    op.drop_constraint('fk_conversation_current_context_snapshot', 'conversation', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_artifact_node_revision_id'), table_name='workflow_artifact')
    op.drop_table('workflow_artifact')
    op.drop_index(op.f('ix_conversation_attachment_conversation_id'), table_name='conversation_attachment')
    op.drop_table('conversation_attachment')
    op.drop_index(op.f('ix_agent_delegation_conversation_id'), table_name='agent_delegation')
    op.drop_table('agent_delegation')
    op.drop_index(op.f('ix_workflow_node_revision_node_instance_id'), table_name='workflow_node_revision')
    op.drop_table('workflow_node_revision')
    op.drop_index('uq_workflow_node_active_execution', table_name='workflow_node_execution')
    op.drop_index('ix_workflow_node_execution_status', table_name='workflow_node_execution')
    op.drop_index(op.f('ix_workflow_node_execution_node_instance_id'), table_name='workflow_node_execution')
    op.drop_table('workflow_node_execution')
    op.drop_index(op.f('ix_workflow_gate_result_node_instance_id'), table_name='workflow_gate_result')
    op.drop_table('workflow_gate_result')
    op.drop_index(op.f('ix_workflow_confirmation_node_instance_id'), table_name='workflow_confirmation')
    op.drop_table('workflow_confirmation')
    op.drop_index(op.f('ix_project_spec_binding_project_id'), table_name='project_spec_binding')
    op.drop_table('project_spec_binding')
    op.drop_index('ix_conversation_message_status', table_name='conversation_message')
    op.drop_index(op.f('ix_conversation_message_conversation_id'), table_name='conversation_message')
    op.drop_table('conversation_message')
    op.drop_index(op.f('ix_workflow_node_instance_workflow_instance_id'), table_name='workflow_node_instance')
    op.drop_table('workflow_node_instance')
    op.drop_index(op.f('ix_workflow_event_workflow_instance_id'), table_name='workflow_event')
    op.drop_table('workflow_event')
    op.drop_index(op.f('ix_project_spec_location_repository_id'), table_name='project_spec_location')
    op.drop_index(op.f('ix_project_spec_location_project_id'), table_name='project_spec_location')
    op.drop_table('project_spec_location')
    op.drop_index(op.f('ix_conversation_context_snapshot_conversation_id'), table_name='conversation_context_snapshot')
    op.drop_table('conversation_context_snapshot')
    op.drop_index('uq_conversation_main_agent', table_name='conversation_agent')
    op.drop_index(op.f('ix_conversation_agent_conversation_id'), table_name='conversation_agent')
    op.drop_table('conversation_agent')
    op.drop_index(op.f('ix_workflow_instance_project_id'), table_name='workflow_instance')
    op.drop_index(op.f('ix_workflow_instance_namespace_id'), table_name='workflow_instance')
    op.drop_table('workflow_instance')
    op.drop_index(op.f('ix_project_repository_project_id'), table_name='project_repository')
    op.drop_table('project_repository')
    op.drop_index(op.f('ix_project_member_user_id'), table_name='project_member')
    op.drop_index(op.f('ix_project_member_project_id'), table_name='project_member')
    op.drop_table('project_member')
    op.drop_index(op.f('ix_conversation_project_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_namespace_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_creator_id'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_workflow_node_definition_template_version_id'), table_name='workflow_node_definition')
    op.drop_table('workflow_node_definition')
    op.drop_index(op.f('ix_workflow_edge_definition_template_version_id'), table_name='workflow_edge_definition')
    op.drop_table('workflow_edge_definition')
    op.drop_index(op.f('ix_project_namespace_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_namespace_workflow_enablement_namespace_id'), table_name='namespace_workflow_enablement')
    op.drop_table('namespace_workflow_enablement')
    op.drop_index(op.f('ix_workflow_template_version_template_id'), table_name='workflow_template_version')
    op.drop_table('workflow_template_version')
    op.drop_table('workflow_application')
    op.drop_index(op.f('ix_spec_standard_version_standard_id'), table_name='spec_standard_version')
    op.drop_table('spec_standard_version')
    op.drop_index('uq_workflow_template_platform_slug', table_name='workflow_template')
    op.drop_index(op.f('ix_workflow_template_namespace_id'), table_name='workflow_template')
    op.drop_table('workflow_template')
    op.drop_index('uq_spec_standard_platform_slug', table_name='spec_standard')
    op.drop_index(op.f('ix_spec_standard_namespace_id'), table_name='spec_standard')
    op.drop_table('spec_standard')
    # PostgreSQL enum types are schema objects and survive table removal unless
    # they are dropped explicitly. Keep downgrade/upgrade round trips clean.
    for enum_name in (
        'artifactstoragetype',
        'attachmentscanstatus',
        'delegationstatus',
        'workflowexecutionstatus',
        'workflowgatetype',
        'confirmationdecision',
        'specbindingstatus',
        'conversationmessagestatus',
        'messagetargettype',
        'messageauthortype',
        'workflownodestatus',
        'speclocationstatus',
        'speclocationtype',
        'conversationagentrole',
        'workflowinstancestatus',
        'repositorystatus',
        'conversationstatus',
        'conversationvisibility',
        'conversationmode',
        'confirmationmode',
        'workflownodetype',
        'projectstatus',
        'workflowversionstatus',
        'specversionstatus',
        'workflowtemplatestatus',
        'workflowscopetype',
        'specscopetype',
    ):
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
