/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutSystemRuntimesRouteImport } from './routes/_layout/system.runtimes'
import { Route as LayoutSystemNamespacesRouteImport } from './routes/_layout/system.namespaces'
import { Route as LayoutSystemLlmProvidersRouteImport } from './routes/_layout/system.llm-providers'
import { Route as LayoutSystemHarnessesRouteImport } from './routes/_layout/system.harnesses'
import { Route as LayoutSystemAgentsRouteImport } from './routes/_layout/system.agents'
import { Route as LayoutSystemRuntimesArtifactsRouteImport } from './routes/_layout/system.runtimes_.artifacts'
import { Route as LayoutSystemAgentsAgentIdRouteImport } from './routes/_layout/system.agents.$agentId'
import { Route as LayoutSystemRuntimesTasksTaskIdRouteImport } from './routes/_layout/system.runtimes_.tasks.$taskId'
import { Route as LayoutSystemRuntimesReleasesReleaseIdRouteImport } from './routes/_layout/system.runtimes_.releases.$releaseId'
import { Route as LayoutSystemRuntimesNodesNodeIdRouteImport } from './routes/_layout/system.runtimes_.nodes.$nodeId'
import { Route as LayoutSystemNamespacesNamespaceIdMembersRouteImport } from './routes/_layout/system.namespaces.$namespaceId.members'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemRuntimesRoute = LayoutSystemRuntimesRouteImport.update({
  id: '/system/runtimes',
  path: '/system/runtimes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemNamespacesRoute = LayoutSystemNamespacesRouteImport.update({
  id: '/system/namespaces',
  path: '/system/namespaces',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemLlmProvidersRoute =
  LayoutSystemLlmProvidersRouteImport.update({
    id: '/system/llm-providers',
    path: '/system/llm-providers',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSystemHarnessesRoute = LayoutSystemHarnessesRouteImport.update({
  id: '/system/harnesses',
  path: '/system/harnesses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemAgentsRoute = LayoutSystemAgentsRouteImport.update({
  id: '/system/agents',
  path: '/system/agents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemRuntimesArtifactsRoute =
  LayoutSystemRuntimesArtifactsRouteImport.update({
    id: '/system/runtimes_/artifacts',
    path: '/system/runtimes/artifacts',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSystemAgentsAgentIdRoute =
  LayoutSystemAgentsAgentIdRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => LayoutSystemAgentsRoute,
  } as any)
const LayoutSystemRuntimesTasksTaskIdRoute =
  LayoutSystemRuntimesTasksTaskIdRouteImport.update({
    id: '/system/runtimes_/tasks/$taskId',
    path: '/system/runtimes/tasks/$taskId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSystemRuntimesReleasesReleaseIdRoute =
  LayoutSystemRuntimesReleasesReleaseIdRouteImport.update({
    id: '/system/runtimes_/releases/$releaseId',
    path: '/system/runtimes/releases/$releaseId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSystemRuntimesNodesNodeIdRoute =
  LayoutSystemRuntimesNodesNodeIdRouteImport.update({
    id: '/system/runtimes_/nodes/$nodeId',
    path: '/system/runtimes/nodes/$nodeId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSystemNamespacesNamespaceIdMembersRoute =
  LayoutSystemNamespacesNamespaceIdMembersRouteImport.update({
    id: '/$namespaceId/members',
    path: '/$namespaceId/members',
    getParentRoute: () => LayoutSystemNamespacesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/system/agents': typeof LayoutSystemAgentsRouteWithChildren
  '/system/harnesses': typeof LayoutSystemHarnessesRoute
  '/system/llm-providers': typeof LayoutSystemLlmProvidersRoute
  '/system/namespaces': typeof LayoutSystemNamespacesRouteWithChildren
  '/system/runtimes': typeof LayoutSystemRuntimesRoute
  '/system/agents/$agentId': typeof LayoutSystemAgentsAgentIdRoute
  '/system/runtimes/artifacts': typeof LayoutSystemRuntimesArtifactsRoute
  '/system/namespaces/$namespaceId/members': typeof LayoutSystemNamespacesNamespaceIdMembersRoute
  '/system/runtimes/nodes/$nodeId': typeof LayoutSystemRuntimesNodesNodeIdRoute
  '/system/runtimes/releases/$releaseId': typeof LayoutSystemRuntimesReleasesReleaseIdRoute
  '/system/runtimes/tasks/$taskId': typeof LayoutSystemRuntimesTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/system/agents': typeof LayoutSystemAgentsRouteWithChildren
  '/system/harnesses': typeof LayoutSystemHarnessesRoute
  '/system/llm-providers': typeof LayoutSystemLlmProvidersRoute
  '/system/namespaces': typeof LayoutSystemNamespacesRouteWithChildren
  '/system/runtimes': typeof LayoutSystemRuntimesRoute
  '/system/agents/$agentId': typeof LayoutSystemAgentsAgentIdRoute
  '/system/runtimes/artifacts': typeof LayoutSystemRuntimesArtifactsRoute
  '/system/namespaces/$namespaceId/members': typeof LayoutSystemNamespacesNamespaceIdMembersRoute
  '/system/runtimes/nodes/$nodeId': typeof LayoutSystemRuntimesNodesNodeIdRoute
  '/system/runtimes/releases/$releaseId': typeof LayoutSystemRuntimesReleasesReleaseIdRoute
  '/system/runtimes/tasks/$taskId': typeof LayoutSystemRuntimesTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/system/agents': typeof LayoutSystemAgentsRouteWithChildren
  '/_layout/system/harnesses': typeof LayoutSystemHarnessesRoute
  '/_layout/system/llm-providers': typeof LayoutSystemLlmProvidersRoute
  '/_layout/system/namespaces': typeof LayoutSystemNamespacesRouteWithChildren
  '/_layout/system/runtimes': typeof LayoutSystemRuntimesRoute
  '/_layout/system/agents/$agentId': typeof LayoutSystemAgentsAgentIdRoute
  '/_layout/system/runtimes_/artifacts': typeof LayoutSystemRuntimesArtifactsRoute
  '/_layout/system/namespaces/$namespaceId/members': typeof LayoutSystemNamespacesNamespaceIdMembersRoute
  '/_layout/system/runtimes_/nodes/$nodeId': typeof LayoutSystemRuntimesNodesNodeIdRoute
  '/_layout/system/runtimes_/releases/$releaseId': typeof LayoutSystemRuntimesReleasesReleaseIdRoute
  '/_layout/system/runtimes_/tasks/$taskId': typeof LayoutSystemRuntimesTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/system/agents'
    | '/system/harnesses'
    | '/system/llm-providers'
    | '/system/namespaces'
    | '/system/runtimes'
    | '/system/agents/$agentId'
    | '/system/runtimes/artifacts'
    | '/system/namespaces/$namespaceId/members'
    | '/system/runtimes/nodes/$nodeId'
    | '/system/runtimes/releases/$releaseId'
    | '/system/runtimes/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/system/agents'
    | '/system/harnesses'
    | '/system/llm-providers'
    | '/system/namespaces'
    | '/system/runtimes'
    | '/system/agents/$agentId'
    | '/system/runtimes/artifacts'
    | '/system/namespaces/$namespaceId/members'
    | '/system/runtimes/nodes/$nodeId'
    | '/system/runtimes/releases/$releaseId'
    | '/system/runtimes/tasks/$taskId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/system/agents'
    | '/_layout/system/harnesses'
    | '/_layout/system/llm-providers'
    | '/_layout/system/namespaces'
    | '/_layout/system/runtimes'
    | '/_layout/system/agents/$agentId'
    | '/_layout/system/runtimes_/artifacts'
    | '/_layout/system/namespaces/$namespaceId/members'
    | '/_layout/system/runtimes_/nodes/$nodeId'
    | '/_layout/system/runtimes_/releases/$releaseId'
    | '/_layout/system/runtimes_/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/runtimes': {
      id: '/_layout/system/runtimes'
      path: '/system/runtimes'
      fullPath: '/system/runtimes'
      preLoaderRoute: typeof LayoutSystemRuntimesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/namespaces': {
      id: '/_layout/system/namespaces'
      path: '/system/namespaces'
      fullPath: '/system/namespaces'
      preLoaderRoute: typeof LayoutSystemNamespacesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/llm-providers': {
      id: '/_layout/system/llm-providers'
      path: '/system/llm-providers'
      fullPath: '/system/llm-providers'
      preLoaderRoute: typeof LayoutSystemLlmProvidersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/harnesses': {
      id: '/_layout/system/harnesses'
      path: '/system/harnesses'
      fullPath: '/system/harnesses'
      preLoaderRoute: typeof LayoutSystemHarnessesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/agents': {
      id: '/_layout/system/agents'
      path: '/system/agents'
      fullPath: '/system/agents'
      preLoaderRoute: typeof LayoutSystemAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/runtimes_/artifacts': {
      id: '/_layout/system/runtimes_/artifacts'
      path: '/system/runtimes/artifacts'
      fullPath: '/system/runtimes/artifacts'
      preLoaderRoute: typeof LayoutSystemRuntimesArtifactsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/agents/$agentId': {
      id: '/_layout/system/agents/$agentId'
      path: '/$agentId'
      fullPath: '/system/agents/$agentId'
      preLoaderRoute: typeof LayoutSystemAgentsAgentIdRouteImport
      parentRoute: typeof LayoutSystemAgentsRoute
    }
    '/_layout/system/runtimes_/tasks/$taskId': {
      id: '/_layout/system/runtimes_/tasks/$taskId'
      path: '/system/runtimes/tasks/$taskId'
      fullPath: '/system/runtimes/tasks/$taskId'
      preLoaderRoute: typeof LayoutSystemRuntimesTasksTaskIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/runtimes_/releases/$releaseId': {
      id: '/_layout/system/runtimes_/releases/$releaseId'
      path: '/system/runtimes/releases/$releaseId'
      fullPath: '/system/runtimes/releases/$releaseId'
      preLoaderRoute: typeof LayoutSystemRuntimesReleasesReleaseIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/runtimes_/nodes/$nodeId': {
      id: '/_layout/system/runtimes_/nodes/$nodeId'
      path: '/system/runtimes/nodes/$nodeId'
      fullPath: '/system/runtimes/nodes/$nodeId'
      preLoaderRoute: typeof LayoutSystemRuntimesNodesNodeIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/namespaces/$namespaceId/members': {
      id: '/_layout/system/namespaces/$namespaceId/members'
      path: '/$namespaceId/members'
      fullPath: '/system/namespaces/$namespaceId/members'
      preLoaderRoute: typeof LayoutSystemNamespacesNamespaceIdMembersRouteImport
      parentRoute: typeof LayoutSystemNamespacesRoute
    }
  }
}

interface LayoutSystemAgentsRouteChildren {
  LayoutSystemAgentsAgentIdRoute: typeof LayoutSystemAgentsAgentIdRoute
}

const LayoutSystemAgentsRouteChildren: LayoutSystemAgentsRouteChildren = {
  LayoutSystemAgentsAgentIdRoute: LayoutSystemAgentsAgentIdRoute,
}

const LayoutSystemAgentsRouteWithChildren =
  LayoutSystemAgentsRoute._addFileChildren(LayoutSystemAgentsRouteChildren)

interface LayoutSystemNamespacesRouteChildren {
  LayoutSystemNamespacesNamespaceIdMembersRoute: typeof LayoutSystemNamespacesNamespaceIdMembersRoute
}

const LayoutSystemNamespacesRouteChildren: LayoutSystemNamespacesRouteChildren =
  {
    LayoutSystemNamespacesNamespaceIdMembersRoute:
      LayoutSystemNamespacesNamespaceIdMembersRoute,
  }

const LayoutSystemNamespacesRouteWithChildren =
  LayoutSystemNamespacesRoute._addFileChildren(
    LayoutSystemNamespacesRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutSystemAgentsRoute: typeof LayoutSystemAgentsRouteWithChildren
  LayoutSystemHarnessesRoute: typeof LayoutSystemHarnessesRoute
  LayoutSystemLlmProvidersRoute: typeof LayoutSystemLlmProvidersRoute
  LayoutSystemNamespacesRoute: typeof LayoutSystemNamespacesRouteWithChildren
  LayoutSystemRuntimesRoute: typeof LayoutSystemRuntimesRoute
  LayoutSystemRuntimesArtifactsRoute: typeof LayoutSystemRuntimesArtifactsRoute
  LayoutSystemRuntimesNodesNodeIdRoute: typeof LayoutSystemRuntimesNodesNodeIdRoute
  LayoutSystemRuntimesReleasesReleaseIdRoute: typeof LayoutSystemRuntimesReleasesReleaseIdRoute
  LayoutSystemRuntimesTasksTaskIdRoute: typeof LayoutSystemRuntimesTasksTaskIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutSystemAgentsRoute: LayoutSystemAgentsRouteWithChildren,
  LayoutSystemHarnessesRoute: LayoutSystemHarnessesRoute,
  LayoutSystemLlmProvidersRoute: LayoutSystemLlmProvidersRoute,
  LayoutSystemNamespacesRoute: LayoutSystemNamespacesRouteWithChildren,
  LayoutSystemRuntimesRoute: LayoutSystemRuntimesRoute,
  LayoutSystemRuntimesArtifactsRoute: LayoutSystemRuntimesArtifactsRoute,
  LayoutSystemRuntimesNodesNodeIdRoute: LayoutSystemRuntimesNodesNodeIdRoute,
  LayoutSystemRuntimesReleasesReleaseIdRoute:
    LayoutSystemRuntimesReleasesReleaseIdRoute,
  LayoutSystemRuntimesTasksTaskIdRoute: LayoutSystemRuntimesTasksTaskIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
